### ISSUE TITLE
emuiibo not running on ams

### ISSUE THREAD

**Issue by trueicecold** [XorTroll/emuiibo#10]
Using 7.0.1 with Kosmos 12.1.2 (AMS 0.8.9)

I compiled all from source (latest libstratosphere and latest emuiibo), but using Kosmos Settings, under Background Services, it says it's disabled. tries enabling it from there, didn't do much good...

and of course, I have the boot2.flag in the title.

**Comment by deurk** [comment]
Using AMS 0.8.9 + 7.0.1 works just fine. Have you tried without compiling yourself and just using the latest available releases?

**Comment by deurk** [comment]
Do you have the same crash issue as #17 ?

**Comment by trueicecold** [comment]
Downloaded the release and it's working fine... Can't tell what I did wrong with the build :/
