### ISSUE TITLE
Opening games that use Amiibo causes the switch to freeze

### ISSUE THREAD

**Issue by sonofskywalker3** [XorTroll/emuiibo#102]
First let me say that I appreciate the hard work you've done on this Homebrew, I use it in Atmosphere and it's super stable, but when I use it on SXOS it causes games like BOTW, Mario Odyssey, and Diablo 3 to freeze any time I open them, even with Emuiibo disabled. 

I also know that SXOS hasn't had the best track record with sysmodules, but they've come a long way recently, to that point that the Tesla overlay actually works, so I was wondering if there was any way to get Emuiibo working on SXOS?

I'm running 10.0.1 with SXOS 2.9.5 beta. I do QA for a software company as my job, so I'd be happy to help test or gather logs or whatever if you're willing to look into it.

**Comment by urherenow** [comment]
1) sxos is closed source. No way to know HOW to make things play nice with it.

2) Tesla displaying is not the same thing as Tesla WORKING. Go ahead and enable any module at all in Tesla (edizon, or the system info overlay thing) and back out of it. Now try to open Tesla again, without rebooting. Good luck!

**Comment by lookye** [comment]
Tesla and also emuiibo are not supporting SX. If you have problems, change your CFW.

**Comment by sonofskywalker3** [comment]
@urherenow 

Thank you for the helpful response, that makes sense.

@lookye 

This is pointless and antagonistic, unless you're the developer of either of these homebrew (which you arent), your statement without any citation carries no weight whatsoever, you're just blowing in the wind for no reason.

**Comment by lookye** [comment]
Off-topic: Lol, come over to discord and lets have a talk about who I am.
On-topic: Both Xor and WerWolv only support Atmosphere and do not support SX. So if it does not work for you. You can only get in touch with SX about adding better support to 3rd party stuff __or__ you change to another cfw.

**Comment by XorTroll** [comment]
**Tesla and also emuiibo are not supporting SX. If you have problems, change your CFW.**

**Comment by XorTroll** [comment]
And as others have pointed, no actual way to tell why it might fail on SX OS.

**Comment by sonofskywalker3** [comment]
@XorTroll thank you.

@lookye the problem isn't who you are, it's who you aren't. Without citation or credentials, you spoke for two developers on a request that you have no relation to. When XorTroll says he doesn't support SX, that carries weight, since he's the one writing the code. When urherenow replied, he gave legitimate reasons why fixing the issues may be impossible, which is helpful to understand the problem. You just made an empty statement with nothing to back it up, and now you're ego is hurt because I don't recognize what an expert you are. After all, you have forked lots of repos...

**Comment by XorTroll** [comment]
lookye has helped a lot with this project and many other projects I've made, so you should really take into account what he says.
I am indeed the dev here and I'm probably the one who knows the most about emuiibo, but that's not a reason to only believe me and to complain about others' opinions.

**Comment by sonofskywalker3** [comment]
@XorTroll I appreciate the clarification.

@lookye I apologize for being abrasive

**Comment by XorTroll** [comment]
I'd like to see more people reporting this, because other than that I have little clue what happens.
Maybe sharing the crash report could help, actually

**Comment by sonofskywalker3** [comment]
@XorTroll I'll see what I can do about other people reporting it. How can I share the crash report? There's no error in the Switch logs. For Breath of the Wild and Mario Odyssey it freezes on the screen with Nintendo in the top left, and Nintendo Switch in the bottom right. If I press the home key it blanks the screen. Then I have to hold down the power button for 20 seconds or so to power it off. Then it will power back on normally. 

For Smash Brothers, it will open the game, and I can play spirit mode, but if I go to Amiibo settings, or try to play a regular game, it crashes with an SXOS error code 2162-002 and reboots.

If there's a Homebrew that can dump some logs, or if you can tell me a path to some files you need I'll be happy to provide them. I appreciate you giving this as much attention as you already have, and I do understand if it can't be done because you can't see the source of SXOS.

**Comment by impeeza** [comment]
Hi, the SXOS team make you pay for the CFW, you should get support in the SX support channel. they was who decided his product is closed software and no comply with all industry standards.  So no one beside they will be able to help you.

**Comment by renannn** [comment]
HI, I have the same error on SXOS

**Comment by impeeza** [comment]
For any SXOS issue support CONTACT DIRECTLY TO  XECUTER TEAM they do not use open code nor follow the standards. SO THEY ARE THE ONLY WHO CAN MAKE CORRECTIONS
