### ISSUE TITLE
AMS crash when switching accounts in Animal Crossing

### ISSUE THREAD

**Issue by plaidman** [XorTroll/emuiibo#103]
I'm getting an Atmosphere blue screen not consistently (maybe once per day or two) when switching between accounts in animal crossing. It has been happening in AMS 0.11.1 and 0.12.0, in both cases I was using emuiibo 0.5. AMS fatal report is attached.

Let me know if there's something I can do on my end to fix this, or if there's any other info you want to know about my setup.

[01588243161_0100000000000352.log](https://github.com/XorTroll/emuiibo/files/4566862/01588243161_0100000000000352.log)

**Comment by XorTroll** [comment]
Try again with version 0.6
