### ISSUE TITLE
support for atmosphere 0.12.0

### ISSUE THREAD

**Issue by spling-du-futur** [XorTroll/emuiibo#104]

**Comment by lookye** [comment]
It works fine on latest atmosphere version.

**Comment by spling-du-futur** [comment]
@lookye not for me

**Comment by lookye** [comment]
Then please read this doc. You may set it up not correctly.
https://github.com/XorTroll/emuiibo/blob/master/Usage.md

**Comment by spling-du-futur** [comment]
switched to sx

**Comment by impeeza** [comment]
Good luck
