### ISSUE TITLE
Can't save amiibo progress in smash ultimate

### ISSUE THREAD

**Issue by Andress24** [XorTroll/emuiibo#106]
The title says it all, i have an amiibo without randomized id and when i try to save my amiibo level progress nothing happens, the game recognizes the amiibo and i can play with it, but the moment i try to save my progress it doesn't. 

Sorry if i have some spelling errors english is not my main language.

**Comment by jew-two** [comment]
I'm having a similar problem it wont let me register my amiibo but it does pop up and let me give it a nickname

**Comment by XorTroll** [comment]
Try again with version 0.6
