### ISSUE TITLE
crash on ams 0.12.0

### ISSUE THREAD

**Issue by spling-du-futur** [XorTroll/emuiibo#109]
my problem is ::
when i try to launch tesla ovl for emuiibo, atmosphere crash.
my firmware version is 9.2.0 on sysnand
other overlays work correctly
i have nxtheme installed

sysmodules/kips ::

Tesla
ldn_mitm
emuiibo
sys-con
sys-ftpd-light
sys-tune

it is normal ?

i try to disable all sysmodules except tesla and emuiibo, and it not works.
i also try to remove nxtheme, no change.

**Comment by lookye** [comment]
Make sure to set up everything fresh and with the latest files (all tesla files + emuiibo and its ovl)
https://github.com/XorTroll/emuiibo/blob/master/Usage.md

**Comment by spling-du-futur** [comment]
i do it @lookye

**Comment by spling-du-futur** [comment]
error code 2168-0002
program : 010000000000352

**Comment by spling-du-futur** [comment]
switched to SX OS, the best CFW
