### ISSUE TITLE
Botw chests do not appear

### ISSUE THREAD

**Issue by saikyo15** [XorTroll/emuiibo#11]
Hi, when i use an amiibo, (using AmiiSwap) only some foods spawn but the chests do not appear, i tried with 4 different amiibo but still the same, only foods but no chests, someone know why?

**Comment by lookye** [comment]
Thats not a problem with emuiibo.
Read on the official Nintendo site as all amiibos give different stuff.

**Comment by saikyo15** [comment]
Yeah It give different stuff but i think lot of them give chests with weapons or clothes, i saw some videos and they get chests always, but i only get food😕🤨

**Comment by deurk** [comment]
Completely unrelated to emuiibo. Use Zelda amiibos for chests. Issue can be closed.

**Comment by usuario593** [comment]
No funciona algunos amiibos, solo da pescados y un cofre con un arma aleatoria

**Comment by D3fau4** [comment]
@usuario593 eso no es problema de emuiibo XD eso es tuyo y del juego.

**Comment by usuario593** [comment]
Eso no resuelve nada del problema
