### ISSUE TITLE
Games stuck on main loading screen aftere placing latest version.

### ISSUE THREAD

**Issue by demalmar** [XorTroll/emuiibo#110]
After placing the latest version, Can't run games anymore, stuck in either Nintendo loading screen or first game loading screen. 
Version 0.5 works, 0.5.1 is the one that causes the problem. I have to hard turn off the console since it is not responding.

**Comment by spling-du-futur** [comment]
me too

**Comment by impeeza** [comment]
Are you using Sigpatches?  This is the more common issue on loading games.  Refer to CWF support unless uninstalling emubiio solves the problem

**Comment by demalmar** [comment]
I think I do. I'm not every savvy about pirated ecosystem. It is working on
0.5 i will leave it there.

**Comment by lookye** [comment]
If you dont know, you´re probably missing them. Also you did not provide a clear statement of your problem. Which firmware, CFW and Version of CFW are you using?

**Comment by seblatre** [comment]
I was also stuck on the loading screen of ACNH since the installation of 0.5.1.
With the 0.5 version it worked pretty good
I'm personaly using Firmware 9.2.0 with Atmosphere 0.11.1.

If the 0.5.1 is only a bug release, I don't see why sigpatches would be in cause.

**Comment by spling-du-futur** [comment]
i don't use spatches

**Comment by lookye** [comment]
You should update atmosphere too and try again.

**Comment by deyboisvert** [comment]
with animal crossing, this started happening when they released their newest update, version 1.3.0, so maybe they are intentionally crashing the game when they detect emuiibo.

**Comment by Shadowghost** [comment]
On FW 10.1.0 with AMS 0.14.1, latest tesla and emuiibo 0.5.1 BOTW is stuck on loading screen, ohly hard reset can get you out of there. Without emuiibo BOTW starts fine.
Just wanted to let you know.

**Comment by impeeza** [comment]
I am running EMUMMC with Atmosphère 0.14.1 FW 10.1.0 EMUBIIO 0.5.1, Tesla Nx-ovloader 1.0.6, sys-ftpd-light.
Hekate 5.3.2 with latest Sigpatches and fs patches from https://gbatemp.net/threads/latest-fs-and-acid-patches-for-kosmos.562915/page-24#post-9155443 . 

Zelda BOTW v 1.6.0 DLC V3.0 and everything is going well
Could be you have so many sysmodules loaded. I only set emuiibo and ftpd light for starting automatically

I don't have Animal crossing installed for testing

**Comment by impeeza** [comment]
> with animal crossing, this started happening when they released their newest update, version 1.3.0, so maybe they are intentionally crashing the game when they detect emuiibo.

Version 1.3.0 require firmware 10.0.0 at least

**Comment by masterchan-777** [comment]
Animal Crossing NH (v1.4.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game stuck on first loading screen in an endless loading loop - hard reset required to reboot the console.
Animal Crossing NH (v1.4.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Disabled : game loads fine.
Animal Crossing NH (v1.4.0) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 : game loads fine.
----------------------------------------------------------------------------------------------------------------------------------------------
Zelda Link's Awakening (v1.0.1) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.
Zelda Link's Awakening (v1.0.1) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.
----------------------------------------------------------------------------------------------------------------------------------------------
Zelda BOTW (v1.6.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game stuck on switch logo in an endless loading loop - hard reset required to reboot the console.
Zelda BOTW (v1.6.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Disabled : game loads fine.
Zelda BOTW (v1.6.0) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.
----------------------------------------------------------------------------------------------------------------------------------------------
Shovel Knight Treasure Trove (v 4.1.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.
Shovel Knight Treasure Trove (v 4.1.0) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.
----------------------------------------------------------------------------------------------------------------------------------------------
Super Mario Odyssey (v1.3.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game stuck on switch logo in an endless loading loop - hard reset required to reboot the console.
Super Mario Odyssey (v1.3.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Disabled : game loads fine.
Super Mario Odyssey (v1.3.0) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.

**Comment by masterchan-777** [comment]
Animal Crossing NH (v1.4.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game stuck on first loading screen in an endless loading loop - hard reset required to reboot the console.
Animal Crossing NH (v1.4.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Disabled : game loads fine.
Animal Crossing NH (v1.4.0) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 : game loads fine.

Zelda Link's Awakening (v1.0.1) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.
Zelda Link's Awakening (v1.0.1) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.

Zelda BOTW (v1.6.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game stuck on switch logo in an endless loading loop - hard reset required to reboot the console.
Zelda BOTW (v1.6.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Disabled : game loads fine.
Zelda BOTW (v1.6.0) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.

Shovel Knight Treasure Trove (v 4.1.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.
Shovel Knight Treasure Trove (v 4.1.0) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.

Super Mario Odyssey (v1.3.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game stuck on switch logo in an endless loading loop - hard reset required to reboot the console.
Super Mario Odyssey (v1.3.0) - AMS 0.14.1 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Disabled : game loads fine.
Super Mario Odyssey (v1.3.0) - AMS 0.13.0 w/ Fusee - fw 10.1.0 - Emuiibo 0.5.1 Enabled : game loads fine.

**Comment by RaZer0k** [comment]
Same happen to me... with AMS 0.14.1/spatches in Mario Odyssey i got stuck in loading with AMS 0.13.0 not problem

**Comment by impeeza** [comment]
On the official sigpatches for hekate. Several years are reported this problem, but the solution eas remove/disable sysmodules. Some was tge offending ones. At my switch i inly gave enabkes emubiio y ftpd-light and all games works just fine
