### ISSUE TITLE
[Feature Request] Create a sysmodule to keep emuiibo always active or create a button which turns emuiibo always on in the overlay

### ISSUE THREAD

**Issue by Aliasim800** [XorTroll/emuiibo#113]
I would much prefer a extra button for keeping emuiibo always on in the overlay though theres also nothing wrong with creating another sysmodule for it.
The reason i think this is a good idea because it helps with games that need emuiibo to be active before starting a game. This is more convenient and less frustrating so that you do not need to close the game, activate emuiibo and then open the game again.
I think this would be a nice addition and would like to see this implemented possibly in a future release.
Thank you.

**Comment by XorTroll** [comment]
I don't really understand what you mean here
What do you exactly mean by "keep emuiibo always on in the overlay"?

**Comment by Aliasim800** [comment]
Basically all I mean is that if its possible to make emuiibo always active.

**Comment by XorTroll** [comment]
Always active? If you enable emuiibo it will be active unless you disable it...?

**Comment by impeeza** [comment]
Emuiibo is a Sysmodule and the SDRoot/atmosphere/contents/0100000000000352/flags/boot2.flag file determines if the module is loaded at boot or not.
The only thing you need is this file.
you can enable/disable the emulation BEFORE LAUNCH a game on the OVL menu for emuiibo  (press  L1+ DOWN+R3) altogether and the OVL is displayed  (you need to install Tesla OVL Loader too).

@XorTroll, thanks a lot for all your work.

**Comment by Aliasim800** [comment]
So you can enable emuiibo at boot with some configuration? If so then that is what I mean. Xortroll, you are right in saying that it will be active unless you disable it but what I mean is if there is a way to enable it automatically at boot without having to go into the overlay to turn it on manually.

**Comment by XorTroll** [comment]
Is it really that annoying to open the overlay and turn it on? Can't think of an easy way to configure that without having to mess with config files

**Comment by Aliasim800** [comment]
Like I said, it is just a possibility. It's so that you don't have to remember to enable emuiibo through the overlay so that when you open a game like zelda you won't have to close the game, enable emuiibo and reopen the game since it has to be enabled before the game gets launched.

**Comment by lookye** [comment]
It´s the same as before the overlay came. Enable it via the button combo before you start the game and so on...nothing has really changed in its handling.

**Comment by Aliasim800** [comment]
Your missing the point, the question is if it's possible to enable it at boot instead of enabling it manually through the overlay.

**Comment by lookye** [comment]
That would not be feasible. If you want to use real amiibo figurines or NFC Chips or whatever, you cant use them if emuiibo is intercepting it by force and you cant disable/enable it.

**Comment by Aliasim800** [comment]
Yes that's one thing to consider. You could maybe possibly add a button to the overlay which controls emuiibo being enabled/disabled at boot.

**Comment by lookye** [comment]
And that is why the enable/disable slider is in emuiibos overlay.

**Comment by Aliasim800** [comment]
That does not control whether its enabled/disabled at boot. If you use the slider to turn emuiibo on and reboot it will automatically get switched off.

**Comment by lookye** [comment]
You can still use hekate toolbox to manage enabling/disabling sysmodules so e.g. emuiibo is enabled or disabled. But this is also not feasible imo as you would then force every user to use the toolbox if they want to enable/disable sysmodules.

Imo is there no easier way of handling what only you seem to want.
