### ISSUE TITLE
[Feature Request] Can this support for the sxos 3.0.3beta?

### ISSUE THREAD

**Issue by ReadboySakura** [XorTroll/emuiibo#114]
The SX OS now can run sys-clk lunched by overlays-loader, but when use emuiibo, i can not enter game and when open the overlay menu ,touch the emuiibo ,it crashed .

**Comment by impeeza** [comment]
Any support on SXOS Must he solicited to they. You pay for it.  And they hage vlose cose so no one can make nothingh compatible with them.  They sholud make his software compatible with any other software.  The available homebrew as emuiibo is a open source standard

**Comment by Masamune3210** [comment]
Just have sxos be more like atmosphere and adhere to the existing api, it's not like sx taking more code from Atmos is going to matter any more than what they do already :(

**Comment by XorTroll** [comment]
emuiibo works as expected in any other CFW :P
In case I did want to fix support, as SX is closed source, how could I tell why SX doesn't support emuiibo correctly?
