### ISSUE TITLE
Support for FW 10.0.4

### ISSUE THREAD

**Issue by spling-du-futur** [XorTroll/emuiibo#116]
I have sysnand 9.2.0, emunand 10.0.4 and i want emuiibo on my emunand

**Comment by lookye** [comment]
Read this on how to set up emuiibo.
[Manual](https://github.com/XorTroll/emuiibo/blob/master/Usage.md)

**Comment by spling-du-futur** [comment]
but it is compatible with fw 10.0.4 @lookye

**Comment by spling-du-futur** [comment]
?

**Comment by impeeza** [comment]
Yes, it's compatible

**Comment by spling-du-futur** [comment]
OH YEAH!!!!!!
