### ISSUE TITLE
Cant save Emuiibo on Smash Ultimate

### ISSUE THREAD

**Issue by UserCorrupt** [XorTroll/emuiibo#118]
Still no fix to this, I've been messing around using the Emuiibos on Smash, they load, I can play with them but when I'm done I can't save them. Says it isn't the same amiibo so I figured maybe it's because Emuiibo uses a random amiibo code everytime I try to load one but it says you can save amiibos on games like smash but I can't find a way how. Any help?

**Comment by lookye** [comment]
It only uses a random UUID if you check the box while creating an amiibo. So create one without the random uuid and test again.

**Comment by UserCorrupt** [comment]
I use Amiigo to create them, is there a way I can do it through there?

**Comment by lookye** [comment]
/shrug
You should ask the guy who made it. Never used that homebrew.

**Comment by UserCorrupt** [comment]
@lookye how would you do it normally?

**Comment by lookye** [comment]
Creating them via emutool, copy them onto the sd and thats it.

**Comment by UserCorrupt** [comment]
@lookye do you know what folder it goes in or just the root? I'm still new to this stuff so I'm unsure

**Comment by lookye** [comment]
Please read this: https://github.com/XorTroll/emuiibo/blob/master/Usage.md
