### ISSUE TITLE
Custom keys

### ISSUE THREAD

**Issue by deurk** [XorTroll/emuiibo#12]
Would be great if some customization to keys for combos was possible, for example using ZR instead of Right stick in combination with U/D/L/R.

Would be nice to also have UP as on, DOWN as off, LEFT and RIGHT as previous and next amiibos :)

Thanks.

**Comment by XorTroll** [comment]
Agree.
BTW 0.2 is including HOME button LED blinking when a combo is performed (only 7.x+ sadly) which is super helpful.

**Comment by deurk** [comment]
Very good idea :)

**Comment by XorTroll** [comment]
Combos are no longer a thing with the next version
