### ISSUE TITLE
SX OS

### ISSUE THREAD

**Issue by akumamg** [XorTroll/emuiibo#120]
SX OS crash when trying to launch Emuiibo

**Comment by impeeza** [comment]
If you want support on SX OS ASK TO THEM, THEY CHARGE YOU, YOU PAY FOR IT AND THEY ARE CLOSE SOURCE SO NO BODY APART FROM THEM CAN MAKE ANY SOFTWARE COMPATIBLE WITH THEY.  SO OPEN A ISSUE WITH THEY.
