### ISSUE TITLE
Emuiibo doesn't let Zelda BOTW start

### ISSUE THREAD

**Issue by RenanGallegario** [XorTroll/emuiibo#121]
Hi, I'm using ReiNX 3.0 (latest one until today) and my switch is at 10.1.0, I am using Tesla overlay with everything installed correctly , before starting Zelda BOTW I start emuiibo, but when I start the game it stays in the black loading screen with the nintendo title FOREVER(I've already waited almost 2 hours). I've already tried to start Zelda without emuiibo and it works perfectly. Pls help

**Comment by lookye** [comment]
1. ReiNX is not supported
2. emuiibo need to be updated for 10.1.0 (and the latest atmosphere version) and that update is still pending.

**Comment by RenanGallegario** [comment]
I'm almost sure that ReiNX supports emuiibo, they even wrote that it works on their official guide. But thanks a lot.

**Comment by Masamune3210** [comment]
They might support this project, but this project doesn't support them. They are not always necessarily mutual
