### ISSUE TITLE
Games that use emuiibo crash.

### ISSUE THREAD

**Issue by PewTronPug** [XorTroll/emuiibo#123]
Hey, I've been working at this for 3 days. I'm really interested in this project. But I have also been very frustrated with it. These past few days I have tried everything to get this too work. My issue is that most games (by most I mean all but one.) crash when I try to use the functionality. Smashes amiibo menu will freeze the console if emuiibo is running when i open the amiibo menu. Same for zelda BOTW, hell mario odessey won't even load with it on. My CFW is ReINX normally, and before u say that's the problem. I used atmosphere and it just crashes when I open the menu too emuiibo. SXOS didn't work ofc. But I really would like too know what my issue is. Because I feel f-ing stupid cause I can't figure it out.

Sincerely, Tracey. <3

**Comment by FunkeyMonkey** [comment]
Tracey, are you on Atmosphere 0.14.1? It's not currently updated yet for it. If you want to use Emuiibo you need to be on 13.
