### ISSUE TITLE
emuiibo do not recognized on Tesla Sysmodules nor Kosmos Toolbox

### ISSUE THREAD

**Issue by impeeza** [XorTroll/emuiibo#126]
Hi, using the .zip file provided on version 0.6 of emuiibo, the emuiibo isn't displayed on the sysmodules (1.21) nor Kosmos Tolbox. so you can't disable it on the GUI.

The problem is in the zip file there is no toolbox.json file provided.

I did put a manually created file on the path:
SDRoot\atmosphere\contents\0100000000000352\
With the content:
```
{
    "name"  : "emuiibo",
    "tid"   : "0100000000000352",
    "requires_reboot": true
} 
```

and now the module is displayed on booth applications.

as stated on OVL page:
https://gbatemp.net/threads/ovl-sysmodules-a-tesla-overlay-to-toggle-sysmodules.557455/

`«To detect sysmodules, ovl-sysmodules uses the same system as the Kosmos Toolbox. It looks for toolbox.json files in your /atmosphere/contents/<ProgramID> folders. If your sysmodule doesn't come with one, tell it's developer to add it!»`

so please add the file to the generated zip file.  thanks a lot.

**Comment by XorTroll** [comment]
Last commit is self-explanatory :P

**Comment by impeeza** [comment]
I haven't see the comit🤪 thanks a lot for your effort
