### ISSUE TITLE
Latest emuiibo (0.6) doesn't work on Link's Awakening on latest atmosphere (0.14.4)

### ISSUE THREAD

**Issue by Flocki1987** [XorTroll/emuiibo#127]
I've downloaded version 0.6 and it works flawlessly on the latest atmosphere (0.14.4) except Link's Awakening. On other games there is no issue.

**Comment by lookye** [comment]
It works. I tested it with Links Awakening before we released it.

**Comment by thaikhoa** [comment]
try joycon in handheld mode if it will help. Works for me with Kirby game, other controllers (Nintendo pro controller included) won't support from what I've tested.

**Comment by Flocki1987** [comment]
Mhhh I don't know why but now it is working :/ Didn't change anything...

**Comment by impeeza** [comment]
You Must «Disconnect» the emulated amiibo BEFORE try any action of read or write, and «Connect» when the game ask to do it.  for me works well loading and saving dungeons and getting special stones.
