### ISSUE TITLE
When using the overlay I can only go one folder deep

### ISSUE THREAD

**Issue by hstraten** [XorTroll/emuiibo#129]
Not sure if this is an issue or a feature request (if it works as designed)

When I use the overlay to select an amiibo that is put into folder for easy organisation, you can only go one folder deep.
so fos instance, if you have folder per game : \acnh, \SSBU, etc. you can't have a subfolder for instance \acnh\cards, acnh\figurines etc.

**Comment by XorTroll** [comment]
This is how the overlay works for now, only folders on root are scanned and deeper ones are not currently supported
