### ISSUE TITLE
Other controllers support

### ISSUE THREAD

**Issue by thaikhoa** [XorTroll/emuiibo#130]
Hi,
If it is just me, I couldn't activate emuiibo's amiibo when using with other controllers (Nintendo pro controller included). Joycon works just fine.

Could you please support for all controllers rather than just the joycon?

Thanks for the amazing update recently.

**Comment by XorTroll** [comment]
Known issue, I forgot to support this properly while rewriting emuiibo

**Comment by almircanella** [comment]
@XorTroll , I Wonder if missioncontrol or sys-con leads to some conflict.  A lot of users use these sysmodules as well.

**Comment by XorTroll** [comment]
Unrelated, I do know it's something I forgot to port from old emuiibo

**Comment by thaikhoa** [comment]
Good to know it's a known bug. Is there any incoming update for it to be fixed? Thanks heaps!!!

**Comment by XorTroll** [comment]
I this issue still present?

**Comment by thaikhoa** [comment]
> I this issue still present?

It works flawlessly now. Thank you.

**Comment by XorTroll** [comment]
Great
