### ISSUE TITLE
Emuiibo crashing atmosphere 10.2.0

### ISSUE THREAD

**Issue by Alkovalski** [XorTroll/emuiibo#131]
I've done a fresh install of Atmosphère, got everything from their git, because I accidentally updated to 10.2.0
(and yeah, Ive got the sigpatches, they came from [this](https://gbatemp.net/threads/sigpatches-for-atmosphere-fusee-primary-only.567542/) GBAtemp thread)

Before the update Emuiibo worked fine, but now every single time I select it in tesla overlay, it crashes my console
I've reinstalled emuiibo about 2 or 3 times, tesla and emutool included (after crashing, deleted every file from both and downloaded everything again)

It says here 

> Error Code 2168-0002 (0x4a8)
> Program: 0100000000000352 
> Firmware 10.2.0 (Atmosphère 0.14.4)

(and that bunch of numbers that I don't quite know if they will be helpful here)

Couldn't find anyone else with this same problem

**Comment by lookye** [comment]
Update emuiibo too and make sure the tesla files are also the latest ones. Everything should work as intended.

**Comment by 0fmc07** [comment]
have the same problem, however the atmosphere does not crash, but it tells me "emuiibo has not accessed" I already deleted my emunand and created another but the same problem continues

**Comment by lookye** [comment]
Make sure emuiibo, tesla and also atmosphere + firmware are on their latest versions.

**Comment by 0fmc07** [comment]
Everything is in the latest versions

**Comment by lookye** [comment]
So you have this setup:
Firmware: 10.2.0
AMS: 0.14.4
emuiibo 0.6 + its 0.6 overlay
tesla-menu: 1.1.3
nx-ovlloader: 1.0.6

**Comment by 0fmc07** [comment]
Of course, I actually have a post right here on github in emuiibo and there are screenshots where a user was supporting me but the problem continues despite having made a new emunand, the post is called "I have to update to 1.2.0?

**Comment by lookye** [comment]
You dont need to recreate your emunand lol. Just have everything up2date. Works on my machine. You may come to discord as its easier: https://discord.gg/3KpFyaH

**Comment by 0fmc07** [comment]
in fact a user here gave me his sd folders but nothing works ... I don't know what I'm doing wrong or why it won't open ... the user is @impeeza

**Comment by 0fmc07** [comment]
![IMG_20200928_002956_807](https://user-images.githubusercontent.com/71985747/94839534-c05de700-03dc-11eb-9605-c327c3238987.jpg)
We did tests by putting the nsp file of version 0.5.1 of emuiibo and it opened but atmos crashed

**Comment by 0fmc07** [comment]
![IMG_20200928_003242_781](https://user-images.githubusercontent.com/71985747/94839654-e4b9c380-03dc-11eb-8e1b-5b3c54ff86ce.jpg)
![IMG_20200928_005706_504](https://user-images.githubusercontent.com/71985747/94839680-f00cef00-03dc-11eb-8b7f-aa2c31aabeef.jpg)

**Comment by 0fmc07** [comment]
using sysmodules it didn't let me put it on, and in emuiibo it didn't open me to turn it on or choose amiibo, the capture where it crashed is when we use the nsp file of version 0.5.1

**Comment by lookye** [comment]
I see from the picture above youre using wrong files, otherwise the overlay would detect the emuiibo version. As i said. use the latest release + its overlay.

**Comment by 0fmc07** [comment]
I still have the same problem, the .nsp file of version 0.6.0 does not want to open from tesla, if I put the one of version 0.5.1 it opens it with an error in atmos, but with the one of 0.6.0 there is no way, I don't know but I think I'm the only one with the problem, I already formatted the sd and everything ... but nothing works or does emuiibo work

**Comment by 0fmc07** [comment]
I have all the files updated to the latest version, but strangely, emuiibo cannot be accessed, I don't know what else to do or who to ask for help

**Comment by OldGnashburg** [comment]
I'm having the same issue. Emuiibo will not turn on either. I deleted folder in contents and did a fresh install. AMS 0.14.4 FW 10.2.0 latest Tesla, Emuiibo.

**Comment by lookye** [comment]
You need to update the emuiibo overlay file too.
