### ISSUE TITLE
Creating a broken "miis" and failing to start the module after the second time due to it

### ISSUE THREAD

**Issue by xMELOSx** [XorTroll/emuiibo#135]
For some reason, an empty "miis" folder is created that cannot be deleted.
Also, if I don't rename the folder, the module seems to become unbootable.

This may be due to the SD being exFAT, so I'll try to see if this improves when I have time.

System : 10.2.0
AMS 0.14.4|S
Deapsea 1.7.2
Hekate 5.3.3
emuiibo 0.6

**Comment by XorTroll** [comment]
If you have exFAT on your SD, I'm pretty sure that's the issue. Switch to FAT32, using exFAT is too risky

**Comment by xMELOSx** [comment]
When I tried converting to FAT32, it seems that a 2-byte character (e.g. Japanese) in the Mii nickname will be garbled and an inaccessible folder will be generated.
It works by changing the nickname to alphanumeric characters.
