### ISSUE TITLE
"emuiibo was not accessed" Atmosphere 0.14.4 + emuiibo 0.6

### ISSUE THREAD

**Issue by FONZD** [XorTroll/emuiibo#136]
Hi,

I've done a fresh install of emuiibo 0.6 yesterday and it was working fine (tested on botw + unlimited amiibo/day cheat).
This morning, I want to test it again but nothing was working and in the overlay i can see "emuiibo was not accessed" .

After many searches, I have found what was causing this problem:
The "miis" folder inside "emuiibo".
On first try all is working fine but after a reboot emuiibo detects a Mii created by my son named 'léonarrrr!' and creates a 'corrupted' folder named '0 - lﾃｩonarrrr!'.
This folder can't be deleted with DBI (MTP) or NX-Shell but can be seen on PC.
If I delete this folder all is working fine on first boot but not on second,
if I go to settings and remane the Mii into 'leonarrrr!' it works fine.
So there is something to do with this special character "é".

THX for all your hard work ! ;)

**Comment by cpulley** [comment]
To add onto this, I had a mii with the "<" character in its name. On boot, this would cause the switch to freeze a bit (audio from BootSoundNx would freeze every quarter-second or so) and emuiibo would fail to load. After renaming the mii, emuiibo loads perfectly.

If you'd like, I have crash reports and dumps, though I assume this'll be easy to replicate ;)

**Comment by lovelydumpling** [comment]
I'm having this same issue but I don't have any miis. I can't figure out what's causing it. The sysmodule doesn't seem to be loading according to the sysmodules tesla menu.

**Comment by lookye** [comment]
Make sure to have the latest Atmosphere version and everything else is also on its latest version and applied correctly.
https://github.com/XorTroll/emuiibo/blob/master/Usage.md

**Comment by lovelydumpling** [comment]
Yep that was the issue. Out of date Atmosphere (was still on 13). All good now!

**Comment by lookye** [comment]
@FONZD Did you solve your problem?

**Comment by FONZD** [comment]
@lookye XorTroll did it. changelog 0.6.1: When exporting system miis on startup, now emuiibo doesn't use the mii's name as the mii folder's name, the mii's name is written to a name.txt file instead to avoid potential FS issues with non-UTF8 names, and the mii folder's name will just be an index.

**Comment by lookye** [comment]
So this issue is solved yeah?
