### ISSUE TITLE
SSBU: Impossible to "remove Amiibo" after saving

### ISSUE THREAD

**Issue by Star-X555** [XorTroll/emuiibo#139]
There doesn't appear to be any way to properly "remove" the Amiibo after saving.  Changing the virtual amiibo or turning off amiibo emulation does nothing, it just gets stuck at the "saving complete please remove amiibo" screen.  The only way to exit from that point on is to go to the home menu.

**Comment by lookye** [comment]
You click on the same amiibo within emuiibo again, so it gets removed, similiar to how you would do it with a real amiibo.
Please read the instructions.
https://github.com/XorTroll/emuiibo/blob/master/Usage.md

**Comment by lookye** [comment]
@Star-X555 Did you solve your problem?

**Comment by XorTroll** [comment]
This should be fixed on latest releases
