### ISSUE TITLE
Makefile adjustment

### ISSUE THREAD

**Issue by urherenow** [XorTroll/emuiibo#14]
This bit needs to be corrected in the makefile. Paths with drive letters aren't appropriate. You also need to check if the folders exist, and create them if they don't, before trying to copy a file into them.

@rm -rf f:/atmosphere/titles/0100000000000352/exefs.nsp
	@cp $(OUTPUT).nsp f:/atmosphere/titles/0100000000000352/exefs.nsp

**Comment by deurk** [comment]
Actually already taken care of in #1 :)

@XorTroll Maybe merge it in?
