### ISSUE TITLE
Failed to enable Emuiibo 'emuiibo was not accessed'

### ISSUE THREAD

**Issue by ClockBlock** [XorTroll/emuiibo#140]
Hi,

I'm running 

10.1.0 / AMS 0.14.16
Emuiibo + Overlay 0.6.0
Tesla 1.1.3
Nx-ovlloader 1.0.6

When i activate Tesla it shows emuiibo + version in the list (and few others).
Choosing emuiibo and pressing 'A' just shows an empty list and the message 'emuiibo was not accessed'.

Emuiibo must be kind of working, despite the fact that its not longer shown in the Homebrew list (Album 'App'), 
cause it did create the Mii Folder.

Does it run in some kind of background mode? Can it somehow be configured?

I've read about a similar issue, and tried to rename the Mii (it had only one letter), 
but that didnt solve the problem.

Looks like more people having this problem.

Thx in advance

**Comment by didak01** [comment]
Did you resolve this? How did you do? :(

**Comment by lookye** [comment]
Reading and following this will help you: https://github.com/XorTroll/emuiibo/blob/master/Usage.md

**Comment by didak01** [comment]
Hi lookye. Thanks for your prompt answer. Unfortunately I did, and is not working yet. Shows emuiibo was not accessed. I double checked folders, files, paths and everything is according to written on usage.md. does This issue is caused by user? I mean... Is definitely my fault? :(

**Comment by XorTroll** [comment]
Update atmosphere, and always make sure to have both ams and emuiibo (well, and every sysmodule) updated
