### ISSUE TITLE
Still issues with Atm 14?

### ISSUE THREAD

**Issue by ClockBlock** [XorTroll/emuiibo#141]
Hey

thanks a lot for your awesome work.

I just downloaded the 0.61 version and noticed that emuiibo cant be activated.
The menu shows that its turned off and there is no way to change that.
Is that still an Atm 14 issue

Thx

**Comment by lookye** [comment]
Did you update the emuiibo.ovl too?

**Comment by ClockBlock** [comment]
Yes

i did delete the old files and put the new ones from the 0.61 downl in the overlay and contents folders

**Comment by ClockBlock** [comment]
![20201027_201230](https://user-images.githubusercontent.com/73080259/97350966-70febf80-1891-11eb-93cd-e0489a33a68e.jpg)
![20201027_201239](https://user-images.githubusercontent.com/73080259/97350988-78be6400-1891-11eb-9d0f-5770621ce397.jpg)

**Comment by lookye** [comment]
In the first picture...click on emuiibo and enable the slider and thats it. You need a json file to enable/disable sysmodules via the overlay where you want to enable e.g. emuiibo.

**Comment by ClockBlock** [comment]
![20201027_205117](https://user-images.githubusercontent.com/73080259/97355013-93470c00-1896-11eb-8a43-889fbd4c3e96.jpg)

So...where do i get this json file to enable/disable emuiibo?

**Comment by lookye** [comment]
Its included in the release. Please make sure to install the sysmodule freshly and the overlay too. Reboot the console and everything should work as intended.

**Comment by ClockBlock** [comment]
The problem was the person in front of the screen...xD

It still didnt worked, but a quick check of the Atm version revealed -> Atm 14.1 

With Atm 14.4 now its working as you described it.
Will test it ingame now.

Thanks a lot mate. Much appreciated
