### ISSUE TITLE
Bug when generating all and uploading via FTP

### ISSUE THREAD

**Issue by 1DontEx1st** [XorTroll/emuiibo#142]
How to recreate:

1. Load Emutool
2. Tick _Upload generated amiibos to FTP_
3. Enter ftp address & port
4. Click _Create virtual amiibo_

Error is:
Caught exception (ArgumentNullException) at Button1_Click

Value cannot be null
Parameter name: path1

**Comment by ZomoXYZ** [comment]
I'm still having this issue v0.6.3

**Comment by ZomoXYZ** [comment]
Looking at [MainForm.cs:283](https://github.com/XorTroll/emuiibo/blob/77ab09b21e64ab375179d71c196c70b6acbf6fb2/emutool/emutool/MainForm.cs#L283), `actual_base_dir` is currently null according to the error.

`actual_base_dir` is set to be the original `base_dir`, which is initialized as null and then never touched. I believe removing the [if statement](https://github.com/XorTroll/emuiibo/blob/77ab09b21e64ab375179d71c196c70b6acbf6fb2/emutool/emutool/MainForm.cs#L237) would fix this.

I made a pull request that should fix this #176, but I don't have the tools installed to run C# and test this.

**Comment by XorTroll** [comment]
[Release.zip](https://github.com/XorTroll/emuiibo/files/6409911/Release.zip)

Can you reproduce it with this build?

**Comment by Xbox-360-1063** [comment]
Well no one seemed to have responded but the transfer all + ftp option works in the build you uploaded

**Comment by ArchOwlen** [comment]
The release.zip posted above solved the issue for me!
