### ISSUE TITLE
The remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by Forenzo** [XorTroll/emuiibo#143]
Every time I try to open the emutools application it just crashes and returns this message. I have the latest NET framework and an internet connection so I don't see why it won't work.

**Comment by lookye** [comment]
AmiiboAPI is offline since a few days, this can happen and its not emuiibos fault.

**Comment by Forenzo** [comment]
What exactly is AmiboAPI? Do I have to use this online system?

**Comment by formerlyKnownAsLagzilla** [comment]
https://github.com/N3evin/AmiiboAPI

git clone https://github.com/N3evin/AmiiboAPI.git

cd AmiiboAPI

openssl req -x509 -nodes -newkey -keyout amii.key -out amii.pem -days 365

edit app.py
```python
@@ -24,6 +24,8 @@
 from routes.character import characterApp
 from routes.amiibo import amiiboApp
 
+from OpenSSL.crypto import *
+import os
 
 app = Flask(__name__)
 
@@ -150,4 +152,5 @@
 
 
 if __name__ == "__main__":
-    app.run(debug=True, extra_files=['database/amiibo.json'])
+    context = ('amii.pem', 'amii.key')
+    app.run(port=443, debug=True, ssl_context=context, extra_files=['database/amiibo.json'])
```

echo "127.0.0.1		www.amiiboapi.com" >> /etc/hosts

**Comment by formerlyKnownAsLagzilla** [comment]
Looks like the server is back up. This can likely be closed.

**Comment by Forenzo** [comment]
Oh cool yeup it's back.
