### ISSUE TITLE
Emutool Not working

### ISSUE THREAD

**Issue by jayymonroe96** [XorTroll/emuiibo#144]
Every time I try to run EmuTool, it keeps giving me a popup, then force closing
the popup reads:
"The remote server returned an error: (502) Bad Gateway"

![Capture](https://user-images.githubusercontent.com/45850803/98447055-faaf5800-20ef-11eb-88f0-d23f0df22de7.PNG)

**Comment by MaymonAdir** [comment]
I have a same issue

**Comment by lookye** [comment]
Not a problem from emuiibo/emutool. The API isnt available at the moment bc the guy who maintains it moves the APIs server.

**Comment by MaymonAdir** [comment]
Will there be a new release?

**Comment by lookye** [comment]
No lol...the guy who maintains the amiiboapi needs to finish migrating his stuff to its new server. And he already said it will be done on the weekend. Just wait and its not worth a 2nd "issue" here.

**Comment by XorTroll** [comment]
This simply has nothing to do with emuiibo, Just wait until AmiiboAPI is working again

**Comment by MaymonAdir** [comment]
OK. But this is Saturday. Does it count as a weekend?

**Comment by MaymonAdir** [comment]
OK, Close the issue. This is working now

**Comment by jayymonroe96** [comment]
Thanks for the information guys, closing now.
