### ISSUE TITLE
Caught Exception (NullReferenceException) at GetAllAmiibos

### ISSUE THREAD

**Issue by possessedlaptop** [XorTroll/emuiibo#145]
I have this issue when trying to open emutool, I tried with the previous releases but all result in the same problem and the program doesn't boot.
NetFramework is up to date and the system's language is in spanish if that info is needed.

![Clipboard02](https://user-images.githubusercontent.com/53954076/98484731-80f69780-21df-11eb-92c5-15b1d5c4e99c.jpg)

**Comment by Slluxx** [comment]
@possessedlaptop can you translate the error message text?
if you view your system events, the event might show up and more detailed logs can be seen.
See this for help: https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by impeeza** [comment]
The error you are getting roughly means «Object Reference to invalid object»  it could mean your .net is bad or missing libraries.

Be sure you have .net 4.52 or newer installed.


Spanish version:
el error que estás obteniendo hace referencia a bibliotecas perdidas o dañadas de .Net, por favor verifica que tienes .Net 4.52 o superior instalado y correcto.

**Comment by Pain160710** [comment]
Hi, i have the same issue as the user "possessedlaptop". My .net is uo to date and i also tried to repair it, but still have the problem.
I'm using Win10 Pro, Version 21H2, Build: 19044.1620, all other .net applications are working fine. Any suggestions on how to fix this?

**Comment by Slluxx** [comment]
I have just downloaded the 0.6.3 release of emutool and it worked just fine (fresh win 10 pro 19044).

Net runtime 6.0.3,
Net SKD 6.0.201
