### ISSUE TITLE
EmuTool not launching

### ISSUE THREAD

**Issue by Kuraion** [XorTroll/emuiibo#146]
No matter which version of the tool I download (I tried the newest 3 versions) the executable isn't launching, it simply does nothing whatsoever when I try to run it. Doesn't matter if I try to run it as an admin or not.

**Comment by Kuraion** [comment]
So I found a workaround myself, it seems to be a compatibility issue with a new Windows 10 update, running the tool with compatibility mode for Windows 8 makes it work. Would be nice if this could get fixed in the next update or at least if the workaround could be written down in the guide somewhere.

**Comment by impeeza** [comment]
Hi, I have the latest Windows 10 version (20H2)in the latest ( 2020 nov 25) patches and EmuTool Works just fine:
![image](https://user-images.githubusercontent.com/41979604/100190909-36526c00-2ebd-11eb-8ce1-f8defb10ee83.png)

**Comment by lookye** [comment]
@Kuraion Do you still have the problem with the latest release?
