### ISSUE TITLE
Same inklings

### ISSUE THREAD

**Issue by edekhudoley** [XorTroll/emuiibo#148]
When using the inkling boy neon green and inkling girl neon pink. inkling boy blue and inkling girl orange show up

**Comment by lookye** [comment]
@edekhudoley Do you have still the same error with latest releases? Make sure emuiibo and atmosphere is up2date.

**Comment by edekhudoley** [comment]
yes i still have the same issue

**Comment by lookye** [comment]
Tested it with latest emuiibo version and can reproduce this.

**Comment by AnalogMan151** [comment]
Does emuiibo support the character variant byte? For example, Mario, Silver Mario and Gold Mario have the same character ID and only differ in character variant. I assume it's the same for the Inklings?

**Comment by SoggieWafflz** [comment]
how do I subscribe to this issue?

**Comment by TheDrawingCoder-Gamer** [comment]
can reproduce with splatoon 3 amiibo; I have an NTAG that scans but using that same ID causes a Splatoon 1 inkling girl to spawn

**Comment by TheDrawingCoder-Gamer** [comment]
could the issue perhaps be that the character part is 0 for inkling?

**Comment by lookye** [comment]
This issue is resolved.
