### ISSUE TITLE
Enable emulation by default

### ISSUE THREAD

**Issue by AmonRaNet** [XorTroll/emuiibo#149]
Maybe I am alone :) but I am suffering a bit from by default disabled emulation. Because emulation can be enabled only after game start (correct me if I am wrong) and I always forget to enable emulation...

I think is is one-line-change here:
https://github.com/XorTroll/emuiibo/blob/770bb41f19e64b5ca34f69556f61e1aa4c7091c1/emuiibo/src/emu.rs#L39

Off-topic question: I would change my-self for me personally :) but I can't establish properly rust/cargo environment for build. Maybe you know ready-to-use docker image or maybe some documentation as start.

**Comment by lookye** [comment]
Emuiibo is meant to be handled like you would use a real amiibo. Also you should always enable emuiibo before you start a game so it can intercept it correctly as stated [here](https://github.com/XorTroll/emuiibo/blob/master/Usage.md).

**Comment by AmonRaNet** [comment]
Emuiibo service runs all the time (by default). Game intercepted only if during game start (or more correct during user session activation) service started/running (which is always true by default) and emulation is On (which is not true by default). I am asking to have possibility to make emulation On by default. By this after boot-up and game start-up I will have intercepted game by default, but with disconnected amiibo. Then in game I simply can select and activate interesting amiibo. 
P.S. Ok I need to add that I use other overlay for control :) which has separation between emulation status and amiibo activation (from here https://github.com/XorTroll/emuiibo/pull/80)
