### ISSUE TITLE
20H Wolf Link

### ISSUE THREAD

**Issue by Naguma93** [XorTroll/emuiibo#15]
How to get 20HP Wolf link? Is it possible on Emuiibo v0.2? And how to do it?

**Comment by lookye** [comment]
Its a hacked amiibo. So this is not a emuiibo issue.

**Comment by Leeserh** [comment]
Download the latest version of [Amiiswap ](https://github.com/FuryBaguette/AmiiSwap/releases) and follow the instructions in the readme. Wolf Link works fine for me with it. Let me know if you need more help.

**Comment by Naguma93** [comment]
I downloaded the latest version of AmiiSwap and did everything according to the instructions in the readme. Wolf link is called only with 3HP instead 20HP, what would *bin I not downloaded.

**Comment by Naguma93** [comment]
> Download the latest version of [Amiiswap ](https://github.com/FuryBaguette/AmiiSwap/releases) and follow the instructions in the readme. Wolf Link works fine for me with it. Let me know if you need more help. Also, I got my amiibos from [here](https://nfc-bank.com/bins.php?categoryid=2)

I downloaded the latest version of AmiiSwap and did everything according to the instructions in the readme. Wolf link is called only with 3HP instead 20HP, what would *bin I not downloaded.

**Comment by XorTroll** [comment]
(comment deleted, don't post here places to get amiibo dumps)

**Comment by lookye** [comment]
Again as stated above:
You need a hacked Wolf Link amiibo as the normal one just have 3 hearts.
If you do NOT have the hacked one grab it from the internet. This is the wrong place to ask as it seems emuiibo works fine for you.

**Comment by Leeserh** [comment]
Sorry! I won't do it again.
