### ISSUE TITLE
wolf link hearts 

### ISSUE THREAD

**Issue by jenkshi** [XorTroll/emuiibo#151]
hi is there a way to edit wolf link's file to get MAX hearts ?

**Comment by lookye** [comment]
Please read the readme from [emuiibo 0.5 changelog](https://github.com/XorTroll/emuiibo/releases/tag/0.5).
Dont see why this needs an issue.

**Comment by Crawfish46** [comment]
The problem is that finding which application can be used to edit these files is difficult, and some have problems using amiitool.

**Comment by lookye** [comment]
This is not a help forum and not an issue with emuiibo.

**Comment by Crawfish46** [comment]
He wondered whether in the future it would be possible to change the data of the amiibos without the need for another program or to create a program only for that use, or at least to say which programs works apart from amiitool.

**Comment by urherenow** [comment]
Changing the data shouldn't be an issue and the tool is Google. You can download the amiibo with 20 hearts. If that doesn't work, then that would be an actual issue with this program.

**Comment by lookye** [comment]
You should also read the link to the changelog i posted above. It is explained how to use modded amiibos and why you need external tools. This is not a bug or anything.

**Comment by Crawfish46** [comment]
I know that what I ask is whether in a new version is available the option to change the data or that they can give more information of programs that can decrypt the files, that’s all.
