### ISSUE TITLE
emuiibo 0.6.1 now crashes when using Atmosphere 0.18.0

### ISSUE THREAD

**Issue by jacoghi** [XorTroll/emuiibo#153]
As pointed out by SciresM, emuiibo relies on the "sm extension", which is now deprecated from Atmosphere.

https://github.com/Atmosphere-NX/Atmosphere/issues/1358

**Comment by XorTroll** [comment]
Known, already pushed the fix to emuiibo's Rust library code, will release as soon as possible

**Comment by jacoghi** [comment]
You're the man, thanks for all your hard work, and I really mean it.

**Comment by impeeza** [comment]
XorTroll. Thanks a lot for your great effort. Regards from Colombia

**Comment by jacoghi** [comment]
Just confirming 0.6.2 fixes the issue and no longer crashes the system. Thanks again for this
