### ISSUE TITLE
0.6.2 emuiibo.ovl   crashes   tesla menu

### ISSUE THREAD

**Issue by rexshao** [XorTroll/emuiibo#154]
open tesla menu ->enable emuiibo -> inject a game ->select an amiibo  ->close the game -> exit emuiibo ovl menu ->reopen emuiibo tesla menu -> find can't connect to emuiibo ->reopen  emuiibo tesla menu again ->tesla menu crashes .

**Comment by XorTroll** [comment]
Can you try again with this overlay?
[emuiibo.zip](https://github.com/XorTroll/emuiibo/files/5927666/emuiibo.zip)

**Comment by XorTroll** [comment]
Try re-downloading the release, I've rebuilt it again and I can't reproduce this

**Comment by jacoghi** [comment]
Just confirming 0.6.2 fixes the issue and no longer crashes the system. Thanks again for this
