### ISSUE TITLE
How do i get my amiibos back into bin files ?

### ISSUE THREAD

**Issue by Mistera91** [XorTroll/emuiibo#155]
I think the title is pretty self-explanatory but one day, I put my bin files into emuiibo and then emuiibo changed them into a folder with the name of the old file. And now that every bin files website are down, I would like to change them into bin files back, or at least have bin files by any way I can (I don't have them on my pc, or anywhere else). I don't know if it's even possible, I don't really know if the amiibos were here by myself or by emuiibo. And btw, please close this if it's too near to piracy.

**Comment by Mistera91** [comment]
Exactly, i want to combine amiibo.json, amiibo.flag and mii-charinfo into a bin amiibo file

**Comment by Mistera91** [comment]
Oh and I might be dum but is this what you were searching for in #86 ?

**Comment by lookye** [comment]
.bin files are not supported anymore as they´re considered warez. If you want .bin dumps from amiibos, search the web for them or buy and dump them on your own.

**Comment by Mistera91** [comment]
> .bin files are not supported anymore as they´re considered warez. If you want .bin dumps from amiibos, search the web for them or buy and dump them on your own.

They are REALLY hard to find, Nintendo closed a bunch of amiibos dumps websites. Thank you anyway.
