### ISSUE TITLE
Emuiibo was not accessed - Tesla Overlayed Menu message

### ISSUE THREAD

**Issue by didak01** [XorTroll/emuiibo#156]
Hi! Hope this post finds you well. 

I installed emuiibo 0.6.2 yesterday and I got emuiibo was not accesed. I cant figure out what is casuing the issue.

May you please enlight me in this regards?

Thank you so much.

**Comment by impeeza** [comment]
Please do not use the bug report for support.  Read the documentation or go to propper suport channels

**Comment by lookye** [comment]
Please read https://github.com/XorTroll/emuiibo/blob/master/Usage.md 

You did not set it up correctly/you use it not correctly.

**Comment by didak01** [comment]
Thanks guys for your guidance. Sorry for the inconveniences.

**Comment by didak01** [comment]
Morning guys. I already check these steps. Everything is set up correctly. However still same message:

Make sure you downloaded all files mentioned above.

Create these folders on your SD (if not present):

sd:/emuiibo/amiibo

sd:/switch/.overlays

Extract all ZIP files and copy the folders on your SD card. It should look like this in the end:

emuiibo: sd:/atmosphere/contents/0100000000000352/exefs.nsp and /flags folder
emuiibo overlay: sd:/switch/.overlays/emuiibo.ovl
tesla-menu: sd:/switch/.overlays/ovlmenu.ovl
nx-ovlloader: sd:/atmosphere/contents/420000000007E51A/exefs.nsp and /flags folder

I don't know what is causing this. On the other hand I don't know where I can get support. 

Sorry for bothering you.

**Comment by XorTroll** [comment]
Are you using the last release of atmosphere?

**Comment by didak01** [comment]
Thanks for your answer! May I ask where can I check my atmosphere current version?

**Comment by lookye** [comment]
On its github release site...please just read the link i posted above.

**Comment by didak01** [comment]
Guys, I figured out that I don't have atmosphere updated and honestly I don't want (know) how to update it. I'm really scared about it. Thanks for all the help that you displayed on me. I will close this thread and whenever I have the courage I will let you know how was it. Thank you very much.

**Comment by Masamune3210** [comment]
Be warned that keeping an old atmos build is pretty much useless and more and more things will start breaking as updates to things are done.
