### ISSUE TITLE
Crash on Atmosphere 0.18.0

### ISSUE THREAD

**Issue by Eds1989** [XorTroll/emuiibo#157]
Just update my EmuMMC to Atmosphere 0.18.0 and Emuiibo to 0.6.2, and have started getting panics on boot.
I get program error for 0100000000000004 with error of:
std: abort (0xFFE)

Having a look at the report.bin, I can see mentions of sys-clk, so I tried keeping Emuiibo installed and removing sys-clk, but then got an Atmosphere crash instead.
If I removed the Emuiibo content folder 0100000000000352, Atmosphere boots without issue.

**Comment by XorTroll** [comment]
Would you mind sending that second crash's report?

**Comment by Eds1989** [comment]
Just to be sure I understand correctly, you mean the one where I had removed sys-clk but left Emuiibo installed?

**Comment by stefluid7** [comment]
Having a similar issue on 0.18.1. Using emuiibo in conjunction with mission control is the no. 1 cause. plz fix. i will attach the log.
[report_0000000032f046ac.zip](https://github.com/XorTroll/emuiibo/files/6006694/report_0000000032f046ac.zip)

**Comment by lookye** [comment]
@stefluid7 You need to update to the latest atmosphere version. Also mission control needs to be updated for the latest atmosphere version (same as emuiibo). Stuff changed in atmosphere and thus emuiibo was updated for it. If you run an older version or outdated homebrews/sysmodules they can get in conflict. You crash is not emuiibos fault.

**Comment by Eds1989** [comment]
As soon as an update for MissionControl is released, I will give it a go and report back, as I too am running MissionControl so it could be the culprit if a couple of us are running the same plugins.

**Comment by thaikhoa** [comment]
I have
atmosphere 0.18
sysnand/ emunand

emuiibo
sys-clk
sys-ftpd light
missioncontrol
sysdvr

Everything works like a charm on my side without a single error.
