### ISSUE TITLE
emuiibo was not accessed

### ISSUE THREAD

**Issue by noc1793** [XorTroll/emuiibo#159]
switch endurance
sxos and atmosphere share  emunand
os=11.0/11.0.1
atmosphere=0.18/0.18.1
nx ovlloader=1.0.6
tesla menu=1.3.3
emuiibo=1.6.2
volemuiibo=1.6.1/1.6.2
game=Zelda: Breath of the Wild/Diablo Ⅲ

desktop open emuiibo and load amiibo
![-76aba903edb1803d](https://user-images.githubusercontent.com/21016380/110191755-2b688980-7e65-11eb-9cab-98c73cad51dc.jpg)

In-game can be used 
![-585d4a8760cb5aab](https://user-images.githubusercontent.com/21016380/110191790-594dce00-7e65-11eb-99e3-7084859d951f.jpg)

In-game it cannot be changed
![-3c706e34ad2c7bdf](https://user-images.githubusercontent.com/21016380/110191943-45ef3280-7e66-11eb-8794-9388520df4e4.jpg)

open multiple times emuiibo，tesla mune collapse 
2021/2 Month before ，can be used normally 
English is not good ，sorry :)

**Comment by lookye** [comment]
Make sure to set up and use emuiibo exactly as described [here](https://github.com/XorTroll/emuiibo/blob/master/Usage.md)

**Comment by noc1793** [comment]
Three people have the same problem.

**Comment by lookye** [comment]
Because they dont set it up correctly or dont use it as intended.

**Comment by SoupD** [comment]
You can downgrade to 17.1 or 18.0

**Comment by lookye** [comment]
Or just set it up as [intended](https://github.com/XorTroll/emuiibo/blob/master/Usage.md) and use the official overlay to avoid problems. This is definitively an user error.

**Comment by SoupD** [comment]
> Or just set it up as [intended](https://github.com/XorTroll/emuiibo/blob/master/Usage.md) and use the official overlay to avoid problems. This is definitively an user error.

Today, I was in the same situation as he was in atmosphere 18.1. I tried to delete emuiibo but failed. Finally, I downgraded to 17.1 and successfully opened it

**Comment by lookye** [comment]
This is not a discussion board but an issue tracker for technical problems. I assure you emuiibo works fine on latest atmosphere version and firmware. The problem sits in front of the console/pc.

**Comment by impeeza** [comment]
Yes! OSI layer 8 for sure 8-P
