### ISSUE TITLE
randomizeUuid not usable?

### ISSUE THREAD

**Issue by ekarbe** [XorTroll/emuiibo#16]
So I tried using the randomizeUuid feature but I guess it breaks the amiibos.
After changing the json back it worked.

Here is an example json:

```json
{
   "applicationAreaSize": 216,
   "firstWriteDate": [
      2019,
      6,
      15
   ],
   "lastWriteDate": [
      2019,
      6,
      15
   ],
   "name": "BOTW Zelda",
   "randomizeUuid": true
}
```

**Comment by XorTroll** [comment]
randomize **d** Uuid -> bad name...

**Comment by ekarbe** [comment]
Sorry but that was jsut an error in my comment.
It actually is randomizeUuid.

**Comment by megarobohobo** [comment]
I'm trying to replicate the issue, but it works fine for me.

**Comment by deurk** [comment]
> Sorry but that was jsut an error in my comment.
> It actually is randomizeUuid.

You made the same typo twice. Can you confirm that your file actually contains the word _randomize**d**Uuid_?

**Comment by ekarbe** [comment]
`randomizeUuid` is the [correct one](https://github.com/XorTroll/emuiibo/blob/f51b07810e8aa292d0f142cfa47e4d00c268e098/source/emu-amiibo.cpp#L184).

**It works after using VSCode instead of Windows Editor.**

**Comment by urherenow** [comment]
Notepad++ will never do you wrong.
