### ISSUE TITLE
Is there a way to use emuiibo for tx/sxos users?

### ISSUE THREAD

**Issue by wbsddgg** [XorTroll/emuiibo#162]
Our vitrual sys version is 11.0 with tx boot 3.1

Is there a way to use emuiibo for tx/sxos users?

Thanks in advance!

**Comment by impeeza** [comment]
No, sx make you pay money for the product, all support should be by them, they make his code closed so no body could give support or make conpatible

**Comment by lookye** [comment]
SX isnt supported. Change to atmosphere. This isnt even worth an open issue. You could have asked on discord or in any homebrew website.

**Comment by XorTroll** [comment]
Ask TX ¯\_(ツ)_/¯
