### ISSUE TITLE
'emuiibo was not accessed' showing in tesla overlay

### ISSUE THREAD

**Issue by supa42** [XorTroll/emuiibo#165]
It appears under 'static' in sysmodules but cannot be changed from the 'off' position. I'm assuming it's due to updating emunand to atmosphere 19.  Hopefully not just me getting this?

**Comment by Masamune3210** [comment]
I'm willing to assume you are correct, atmos rewrote a bunch of things to be in line with the latest hos, which usually causes hell with sysmodules especially those that do any sort of redirection or the like

**Comment by urherenow** [comment]
This repo says "forked from ogniK5377/switch-nfp-mitm", and SciresM specifically said "Homebrew which uses atmosphere extensions (including the mitm API) will need to be re-compiled in order to function on 0.19.0."
