### ISSUE TITLE
SSBU crashes on every new amiibo registration. 

### ISSUE THREAD

**Issue by MadMax1960** [XorTroll/emuiibo#167]
Running on latest atmos and the past couple of versions have made amiibos crash 100% of the time when registering them. I've tried both modded and unmodded smash, and atmos always crash when registering a new amiibo. The entire switch locks up and I need to forcibly shut it off.

**Comment by XorTroll** [comment]
Is this issue still present?

**Comment by MadMax1960** [comment]
I have grown as a person and no longer like smash bros
