### ISSUE TITLE
Crashes on new Atmosphere 0.19.0

### ISSUE THREAD

**Issue by zdmc** [XorTroll/emuiibo#168]
The emuiibo crashes on my Erista console with new Atmo 0.19.0 (kefir 522). The crash report is created in the Atmosphere/crash_reports folder. No log files are created in the emuiibo folder but the subfolder miis is created. With Atmo 0.18.1 (kefir 517) I have no issues and emuiibo works as expected.

**Comment by Andi2207** [comment]
same here. Have you plan a fix @XorTroll ?

Best Regards

**Comment by lookye** [comment]
Emuiibo needs an update for latest Atmosphere version, we are aware of that. But it does not crash on latest firmware and latest atmosphere version.

**Comment by zdmc** [comment]
I didn't test it with current 12.0.0 firmware. My configuration is: 11.0.1 switch firmware + Atmosphere 0.19.0 (kefir 522).

**Comment by Abssenta** [comment]
Same here. FW 11.0.1 + atmosphere 0.19.1. The module is not even loaded at boot. I went back to 0.18 only for this app and it works good. Although it doesn't crash in my console.

**Comment by urherenow** [comment]
Did you try moving its location from /atmosphere/contents to the new place 0.19.1 puts its files to see if it loads? I'm fairly certain that it isn't supposed to be that way, but there *could* be a bug with Atmosphere... (I personally haven't tested anything that lives/lived in contents/ and had a boot2.flag with the new version yet)

**Comment by tsukina22** [comment]
I have firmware 12.0 and Atmosphere 0.19.1, the emuiibo dosen't crash, but dosen't open either, i try to loaded, ask to reboot, but when i try said that "emuiibo was not acessed" and ask to reboot turn it on and reboot again to work, but i already tried and dosen't work, please update it.

**Comment by impeeza** [comment]
> I have firmware 12.0 and Atmosphere 0.19.1, the emuiibo dosen't crash, but dosen't open either, i try to active it, ask to reboot, but when i open the game said that "emuiibo was not acessed" and ask to turn it on and reboot again to work, but i already tried and dosen't work, please update it.

You can always make the necessaries changes to the code and recompile it instead of demand an update which already is work in progress.

Or you can read the other posts and downgrade your firmware and atmosphère versions and get a  working emuiibo

**Comment by tsukina22** [comment]
> > I have firmware 12.0 and Atmosphere 0.19.1, the emuiibo dosen't crash, but dosen't open either, i try to active it, ask to reboot, but when i open the game said that "emuiibo was not acessed" and ask to turn it on and reboot again to work, but i already tried and dosen't work, please update it.
> 
> You can always make the necessaries changes to the code and recompile it instead of demand an update which already is work in progress.
> 
> Or you can read the other posts and downgrade your firmware and atmosphère versions and get a working emuiibo

First, i could totally do this, if i know, but since i don't know how to update the files myself, the only thing i can do is ask for it. 
I don't think you read what i said right, but i didn't demand anything, i just asked "please update it".
And second, how could i know that anybody is working on a update? I'm sorry but i can't read minds, just because people asked here to update dosen't mean that already have a update being worked on. 
I just came here to share my experience that is not crashing just dosen't load, so if you have the need to be rude about it, is not with me.
Thank you for your answer anyway.

**Comment by urherenow** [comment]
Read minds? GTFOH with that. What you need to read, is the list of active issues. If there is already an issue posted, you don't need to post another one. And saying "please update" is unnecessary and redundant. Putting the word "please" in front of it, doesn't make it any more polite, or any less annoying.

**Comment by hrvylein** [comment]
there is a commit that mentions compatibility with atm 0.19 *thumbs up*

is there any eta for the release or can we help you test it?

**Comment by lowburger** [comment]
> there is a commit that mentions compatibility with atm 0.19 _thumbs up_
> 
> is there any eta for the release or can we help you test it?

I have exclusive eta for you! June 15th

**Comment by hrvylein** [comment]
nvm, i compiled it and tested it with some random amiibos. So far no crashes and intercepting games worked. 👍
