### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by YungySSBU** [XorTroll/emuiibo#169]
I have the latest cfw firmware and emuiibo is not working we need an update for it.

**Comment by lookye** [comment]
This is known. There is no need to make duplicate issues (#168 )

**Comment by impeeza** [comment]
If you read the others issues you find is a know problem, so if is so NEEDED for you, always you can reverse engineering the new firmware, make new code, propose pull requests for emuiibos and recompile. Then you can use these great product.

Or, you can politely ask for a solution to a new issue (if is a new unknown issue) or at least read the documentation.
