### ISSUE TITLE
Emuiibo crashes smash

### ISSUE THREAD

**Issue by imnotgonn** [XorTroll/emuiibo#171]
I’ve been trying to get this to work for a while and can’t find anything about it so I’ll leave it here, when I try to use emuiibo on anything it other dose load or crashes. For smash it says “The software is aborting” choosing details gives the following:

Error Code: 2-0069

0
Error:0x25a0b

My switch is on vr 10.1.0 Reinx 3.0 

Help would be greatly appreciated 

![2C36B454-807D-4186-84CB-730B474B1740](https://user-images.githubusercontent.com/83030092/115758217-7df1fc80-a364-11eb-9126-69de7c7b70fc.jpeg)

**Comment by impeeza** [comment]
Emuiibo works fine on atmosphère 0.18.0 you should migrate to atmosphère, reinx has been not updated for more than a year and never give well support for emuiibo

**Comment by lookye** [comment]
Make sure you [set it up correctly](https://github.com/XorTroll/emuiibo/blob/master/Usage.md). Reinx is dead since a long time and not supported.

**Comment by XorTroll** [comment]
Yeah, emuiibo is only expected to work under latest Atmosphere
