### ISSUE TITLE
[BUG] emutool - "Create in the last used path" not working since v0.6.1

### ISSUE THREAD

**Issue by SwiftMove** [XorTroll/emuiibo#172]
[BUG]
I've discovered that the "Create in the last used path" function is no longer working since v0.6.1. I'm still asked where to save an Amiibo even though the "Create in the last used path" box is checked. This feature used to work properly in v0.6.0 and lower, but isn't working in v0.6.1 and higher. I'm sure this probably has something to do with the "Generate all Amiibo's at once" feature.

[FEATURE REQUEST]
Speaking of the "Generate all Amiibo's at once" feature, I'd like to request that an option to only generate all the Amiibo's in a single category be implemented. Certain categories (i.e. Animal Crossing) have a LOT of Amiibo's so using the "Generate all" feature takes way longer to run if I'm only wanting to generate Amiibo's for a single category. So it would be nice to have an option to generate all Amiibo's for a single category as well.

**Comment by Slluxx** [comment]
ill take care of this in a few days.

**Comment by Slluxx** [comment]
this is only the bugfix, not the implementation of the feature request

**Comment by impeeza** [comment]
@Slluxx  I think is better to open a separated issue for the feature request, so it will be east to track his status😀

**Comment by Slluxx** [comment]
@impeeza why would i open an issue for the feature request if i am not the one who wants that lul

**Comment by Slluxx** [comment]
#180 reopened

**Comment by DeadlyVoyage** [comment]
@Siluxx, was the feature request that @SwiftMove made ever added? I was looking forward to that feature as well. Perhaps something like "Generate all amiibos for the selected category"?

**Comment by Slluxx** [comment]
Sorry, i never saw this message.

No, i only fixed the bug and i have no interest in creating anything switch related (I dont even own a switch anymore). Its not too hard to generate all and then only pick the ones you actually want or use [my tool to generate them on the switch](https://github.com/Slluxx/AmiiboGenerator).
