### ISSUE TITLE
Emuiibo not saving in Super Smash Bros

### ISSUE THREAD

**Issue by TomEFFENJones** [XorTroll/emuiibo#174]
I've got the overlay working perfectly fine, and created a Cloud SSBU Amiibo. It loads the Amiibo fine, and I can even battle it, but when it "saves", and I go to load it back in, it resets to level one. I made sure to not have the UUID randomized each time it's loaded. Anyone else have this issue?
I'm on Atmosphere 19.1 and firmware 12.
Edit: I left the Emuiibo Mii as the owner this time, and it saved the data. 
Edit 2: I was able to change the Mii to one from my console, and it save data the first time. Now, when I load the Amiibo back in, after it has gained some levels, it will not save again. It says "The data on this amiibo may have been overwritten by another console. Unable to write to this amiibo."

**Comment by Finncelot** [comment]
I'm having the same issue with the data overwritten message, the first time I use the amiibo it saves fine but if I try to load it up and save it again it won't write the amiibo.

**Comment by TomEFFENJones** [comment]
> 
> 
> I'm having the same issue with the data overwritten message, the first time I use the amiibo it saves fine but if I try to load it up and save it again it won't write the amiibo.

I'm glad I'm not the only one. I tried everything I could think of.
- Left 'Emuiibo' as the Mii
- Loaded the amiibo, trained it to level 5 (one 3 stock match), saved it, quit the game and restarted the Switch. Loaded it again, and it was at level 5, train it another round, go to save it, and then it says the above error
- Tried leaving the 'amiibo' connected until it says to take it off
- Made a new emuiibo
- Tried a different emuiibo
Thank you Xor for the utility, and I hope this is an easy fix!

**Comment by XorTroll** [comment]
Last commit fixes a bug which might cause this. Can you test with this build?

[SdOut.zip](https://github.com/XorTroll/emuiibo/files/6409955/SdOut.zip)

**Comment by TomEFFENJones** [comment]
> 
> 
> Last commit fixes a bug which might cause this. Can you test with this build?
> 
> [SdOut.zip](https://github.com/XorTroll/emuiibo/files/6409955/SdOut.zip)

Sorry for the late reply, I will test this out ASAP and let you know. Thank you, Xor.

**Comment by lowburger** [comment]
> > Last commit fixes a bug which might cause this. Can you test with this build?
> > [SdOut.zip](https://github.com/XorTroll/emuiibo/files/6409955/SdOut.zip)
> 
> Sorry for the late reply, I will test this out ASAP and let you know. Thank you, Xor.

Report issue but never test fix?

**Comment by MyriadShade** [comment]
Issue still happens to me sadly

**Comment by Mr-Socket-bit** [comment]
> Last commit fixes a bug which might cause this. Can you test with this build?
> 
> [SdOut.zip](https://github.com/XorTroll/emuiibo/files/6409955/SdOut.zip)

I also was having this issue. I tried the build you provided and it works fine. I can put away the amiibo, and read it again and the data is as i left it. I can close the software itself and restart it and the data is still intact. Thank you

**Comment by SiTWulf** [comment]
> Last commit fixes a bug which might cause this. Can you test with this build?
> 
> [SdOut.zip](https://github.com/XorTroll/emuiibo/files/6409955/SdOut.zip)

This new version works like a charm!
Not more problems saving changes in Amiibo, this versions rocks!
FW: 12.1 + Atmosphere 20.1
