### ISSUE TITLE
Miitopia not detecting amiibo as intended

### ISSUE THREAD

**Issue by KelvinGomezM** [XorTroll/emuiibo#177]
For the Miitopia demo, it seems to be registering most of the Amiibos as not figures, the NPC just tells you:
 _"I didn't realize you could even get amiibo like this!"_ 
Even with unsupported amiibo, you at least get 3 tickets.

**Comment by lookye** [comment]
Are you on latest Firmware?
Are you using latest Atmosphere release?
Are you using latest emuiibo release?
Which amiibos did you try and what should have happen with these amiibos?

**Comment by KelvinGomezM** [comment]
Tested on 11.0.1 and 12.0.2
Tested on Atmosphere 0.19.3
Using latest Emuiibo release
Tested the Classic Mario and OoT Link amiibo.
The game is supposed to detect any of [these amiibo](https://amiibo.fandom.com/wiki/Miitopia) and grant you clothes based on the characters. Tried with a Physical version of the Ocarina of Time Link amiibo and it had no issues.

**Comment by KelvinGomezM** [comment]
Deleting the amiibo folder and generating new ones with Emutool seems to have fixed it completely.
