### ISSUE TITLE
not being intercepted

### ISSUE THREAD

**Issue by Lostlapis** [XorTroll/emuiibo#178]
so a few months ago emuiibo worked but i recently updated the console and everything else redownloaded it but when ever i try using it and game it always say's current game is not being intercepted i also start it before i start the game

**Comment by Demontion** [comment]
Same here, triple checked directions and reinstalled with overlay multiple times.

**Comment by lookye** [comment]
Works fine if done as described [here](https://github.com/XorTroll/emuiibo/blob/master/Usage.md)

**Comment by Demontion** [comment]
> Works fine if done as described [here](https://github.com/XorTroll/emuiibo/blob/master/Usage.md)

Which I did 3 times. It is now working and intercepting, did not realize it only intercepts successfully when the game is in an amiibo reception state, my bad there. Sometimes still not working but toggling and retrying works. Amiibo aren't working as intended in Monster Hunter Rise but that's for another ticket probably already posted.

**Comment by lookye** [comment]
Skylander stuff are not amiibos and thus not compatible with emuiibo.

**Comment by impeeza** [comment]
The Turbo Charge figurines are "hybrids" of amiibo and Skylander,  they have boot protocols, if you use the actual figurine on a Amiibo compatible sofware is readed as an amiibo, but skylander uses with is own protocol.

https://amiibo.fandom.com/wiki/Turbo_Charge_Donkey_Kong

**Comment by XorTroll** [comment]
Yeah, Skylanders isn't and won't be "supported" by emuiibo since its figurines use a different and not supported protocol in those games
