### ISSUE TITLE
Amiibo's dumped/decrypted save data not being read by game (BOTW Wolf Link)

### ISSUE THREAD

**Issue by TidusWulf** [XorTroll/emuiibo#179]
I've read the instructions but I must have done something wrong. I downloaded a dump of Wolf Link with 20 hearts. I decrypted it with amiitool using a key_retail.bin file. I renamed the dumped/decrypted file to 0x1019C800.bin, then put it in ../Wolf Link/areas/ for the Emuitool generated Wolf Link. I rebooted the console. When I activate the Wolf Link Amiibo in BOTW using Emuiibo, it shows up with 3 hearts instead of 20.

**Comment by impeeza** [comment]
Please read the instructions you are missing some steps, and please **Do not open issues for support** or help, for that, use the correct channels, discord or forums should be the right places

**Comment by TidusWulf** [comment]
Oops. I'm sorry about that. I will find support elsewhere (I re-read instructions and don't see what I'm missing). Sorry for the trouble.

**Comment by impeeza** [comment]
From the readme.md:


Running the following will decrypt the raw dump:

amiitool -d -k <key-file-bin> -i <amiibo-raw-dump-bin> -o <out-decrypted-bin>

You'll have the decrypted app-area section at offset 0xDC on the decrypted dump, of length 0xD8. By saving that as <game-access-id>.bin inside the /areas folder of a virtual amiibo being used by emuiibo
