### ISSUE TITLE
"Current game is not being intercepted"

### ISSUE THREAD

**Issue by Ixaruz** [XorTroll/emuiibo#183]
get message "Current game is not being intercepted" while trying to scan for amiibo (in BOTW).
never used emuiibo before so I dont know if this is just a me-problem.
I also tried most solutions in the other issues.

running switch FW 12.0.3, atmosphere 19.4
only other sysmodules are Noexes and sys-clk.
latest nx-ovlloader and ovlmenu.

Any help would be appreciated.

**Comment by lookye** [comment]
Please follow https://github.com/XorTroll/emuiibo/blob/master/Usage.md strictly. Github issues are not meant for "support"

**Comment by Ixaruz** [comment]
> Please follow https://github.com/XorTroll/emuiibo/blob/master/Usage.md strictly. Github issues are not meant for "support"

alright, ill close the issue. I followed the instructions again, but i doubt it will make a difference.

**Comment by XorTroll** [comment]
If you toggled on emuiibo after launching BOTW that is the issue, always try to enable emuiibo before launching a game since due to technical reasons it won't work with certain games (like BOTW) if emuiibo is enabled later in-game
