### ISSUE TITLE
emuiibo doesn't appear on tesla-menu

### ISSUE THREAD

**Issue by lsycxyj** [XorTroll/emuiibo#184]
I'm using 12.0.3 | AMS0.19.4 with an exFat SD card. And I followed the set-up steps, unset the archiving bits by Hekate tools. However, I can't see "emuiibo" appearing on the menu, while other things like sys modules exist.

**Comment by impeeza** [comment]
Do not use exfat, and update ovlmenu

**Comment by lsycxyj** [comment]
> Do not use exfat, and update ovlmenu

My ovlmenu and nx-ovlloader are of the lastest versions. Is emuiibo imcompatible for exfat?

**Comment by impeeza** [comment]
All Homebrew is incompatible whit exfat, exfat is prune to data errors and SD data damage.
