### ISSUE TITLE
Emutool support for linux

### ISSUE THREAD

**Issue by avicarpio** [XorTroll/emuiibo#186]
Emutool can't be used on Linux systems

**Comment by impeeza** [comment]
That's right, EmuTool is for now a Windows App.  on the documentation and GBATemp page, there is Linux Alternatives, some commands and methods.

**Comment by XorTroll** [comment]
emutool was made with Windows Forms since those programs can be used with mono on non-Windows systems

**Comment by Archargelod** [comment]
Can confirm, everything is working on Debian Linux with "mono-complete" package installed. Would be cool to add that info in Readme. I was really frustrated when only after year I figured by chance that it works this way.

**Comment by XorTroll** [comment]
Fair enough, should mention it in the README

**Comment by AmonRaNet** [comment]
emutool works also under wine. I have tested for ubuntu 16, wine-5.0.3. Only important was to install .NET 4.6.1. As soon it was installed emutool starts to work. Googling for "winetricks dotnet461" for your distribution will help :)  Also I have forced winearch to win32, but I not 100% sure if this is mandatory.
