### ISSUE TITLE
Amiibo does not work in BotW

### ISSUE THREAD

**Issue by Naguma93** [XorTroll/emuiibo#19]
Amiibo does not work in BotW. SSB Link, Majora's Mask Link, 8-bit Link, OoT Link, TP Link, SS Link. Always called fish and chest instead of the items specified in the description. All other amiibo work.

**Comment by Matdu10** [comment]
Same here, with Majora's Mask Link, 8-bit Link and SS Link.

**Comment by lokithewolf** [comment]
had the same problem with Tp link. if its over 11 characters rename and shorten it i cut out the spaces and link and it worked fine.

**Comment by Naguma93** [comment]
Not worked too.

**Comment by lokithewolf** [comment]
Wierd. You are switching the amiibos between uses right?

**Comment by Naguma93** [comment]
Of course. Figures from the list above do not work. The rest amibo work great.

**Comment by Naguma93** [comment]
Sources can not be specified here. But there were many. And one of them is known to you. It is used by all)

**Comment by Leeserh** [comment]
Thanks for your suggestion @lokithewolf . I am unfortunately having the same error even after renaming without using spaces. I can summon Wolf Link, though. Weird.

**Comment by jrhawkins** [comment]
> 
> 
> Thanks for your suggestion @lokithewolf . I am unfortunately having the same error even after renaming without using spaces. I can summon Wolf Link, though. Weird.

I can summon wolf link but he only has 3 hearts instead of 20. Also, Epona does not spawn ever with the TP Link or SSB Link amiibo bin files.I have tried over and over. I have tried with no spaces too. I think the BOTW amiibos. This was with 0.1 and 0.2 builds.

**Comment by Marcotini13** [comment]
I'm having the same problem. Someone know if they are working on it?

**Comment by deuteronx** [comment]
Wolf Link:
Wolf with 3 hearts is always summoned from 20-heart dump.
I assume that the data about 20 heart is stored in amiibo's appdata area. However, I have tried to track the code and found out that the code about checking/reading amiibo's appdata has never been called. 
I think this might relate to how nfp-mitm works. I am new to these switch homebrew things and I have no idea how to fix.

Other Link:
I have found that all variations of Link amiibo also dont work as expected. They instead summon chest box and tons of fish. I found that the code returns amiibo's id correctly but the game might make other requests which are not tapped. I think this also involves with how nfp-mitm works.

**Comment by aaaaaaudrey** [comment]
I have the exact same error. Wolf link works, all other links give a chest and fish.

**Comment by Susanoo1337** [comment]
Here's the list of Amiibo not emulating correctly in BOTW(at least for me, emuuibo 0.2.1, Atmosphere 0.8.10):

Link Raider
8Bit Link
BOTWZelda
BOTWLinkArcher
MMLink
OOTLink
SSBLink
TPLink
(SSBZelda)*

All those amiibo call from a generic loot table containing fish and a chest with either a 1H Sword, 2H Sword or Spear for your corresponding tier(Tutorial/Paraglider/1st Dungeon clear)
The only exception is SSB Zelda which has the Twilight bow replaced by a Royal Shield, the amiibo does not have any shields in its original loot table. NFC tag works flawlessly.
I've tried most of the above with various dumps from the bank as well as dumps from my own amiibo.

**Comment by thb3** [comment]
anyone got a fix to this?

**Comment by goffrier** [comment]
epic
lemme know when xor gets his fingers out of sciresm and actually starts to update his shit

**Comment by usuario593** [comment]
Me sucede lo mismo ¿alguna solucion?

**Comment by XorTroll** [comment]
Duplicate issue
