### ISSUE TITLE
Missing Animal Crossing Sanrio cards.

### ISSUE THREAD

**Issue by TerraFlareKSFL** [XorTroll/emuiibo#192]
@ title.
Just noticed 2 Sanrio character cards are missing (Suppose to be 6 in total)
--#1 Rilla
--#3 Etoile
 Emutool has the other 4 listed, but the 2 listed above are missing.

**Comment by lookye** [comment]
This is not controlled by emutool but via [amiibo API](https://github.com/N3evin/AmiiboAPI).

**Comment by impeeza** [comment]
@lookye thanks

**Comment by TerraFlareKSFL** [comment]
> This is not controlled by emutool but via [amiibo API](https://github.com/N3evin/AmiiboAPI).

I see. Thanks for the info. I reported the issue over to API. Even checked their database and the amiibos are indeed missing.
