### ISSUE TITLE
Inability to save gearsets to Splatoon amiibo

### ISSUE THREAD

**Issue by Kirb99** [XorTroll/emuiibo#193]
Exactly as the title says; I can scan the amiibo just fine, and they recognize that i've 'become friends' with them, but it never saves any gearsets that I try to save to them.
I do not have random uuid turned on and never have.
(also, the neon green and neon pink inkling boy and girl are scanned as blue boy and orange girl respectively; the squid still works as intended however. I do not know why this is-)

**Comment by lookye** [comment]
This is resolved.
