### ISSUE TITLE
Conflicting characters in some amiibo names

### ISSUE THREAD

**Issue by crunchprank** [XorTroll/emuiibo#195]
It looks like when using the option to `Generate amiibos all at once`, there is a problem with the Animal Crossing amiibo `Spork`. I think it may be due to the PAL version of his name `Crackle`. But when the amiibos are created, there is a Spork directory, then a Crackle directory within that:

```
Spork/
└── Crackle
    ├── amiibo.flag
    └── amiibo.json
```

```json
{
  "name": "Spork/Crackle",
  "write_counter": 0,
  "version": 0,
  "mii_charinfo_file": "mii-charinfo.bin",
  "first_write_date": {
    "y": 2021,
    "m": 12,
    "d": 1
  },
```

This may simply be intended, but it seemed off as this appears to be the only one that generates a sub directory.

**Comment by XorTroll** [comment]
Oh, since the amiibo name is "Spork/Crackle", that slash is being treated as a new child directory when creating everything
Yeah, this should be fixed (maybe replacing "/" or "\" characters with something less conflicting, like " " or "_")

**Comment by XorTroll** [comment]
emutool's code now replaces "/" with "_" on amiibo names
