### ISSUE TITLE
How do I enable Emuiibo on the system menu?

### ISSUE THREAD

**Issue by DShip91** [XorTroll/emuiibo#196]
I'm trying to change the nickname and owner of my Mii in Smash but I'm unable to because Emuiibo doesn't seem to be working outside of games. Is there anything I can do?

**Comment by impeeza** [comment]
It's simple you read the instructions on the main page and you will be able to do it

https://github.com/XorTroll/emuiibo#sd-layout

**Comment by DShip91** [comment]
> It's simple you read the instructions on the main page and you will be able to do it
> 
> https://github.com/XorTroll/emuiibo#sd-layout

I did. I can emulate amiibo in games just fine; it's when I try to change the owner in the system menu that it suddenly stops functioning (and bricks the virtual amiibo as a side-effect).

**Comment by urherenow** [comment]
No. You did NOT read it. What you're trying is not here w emuiibo works at all. If you want to change owners and save things like a real amiibo, make yourself some nfc stickers.

"Mii: every amiibo has a mii associated with it (it's "owner"). Internally, miis consist on a 88-byte structure known as "charinfo", so emuiibo stores this data in a file (typically mii-charinfo.bin). For new amiibos, emuiibo uses the console's services to generate a random mii, but for those who would like to use a mii from their console, emuiibo dumps in miis directory the console's miis, so it's just a matter of copying and pasting/replacing charinfo bin files. NOTE: emuiibo contains the charinfo file's name in the JSON (mii_charinfo_file), so if the file ever gets renamed, don't forget to rename it in the JSON too, or emuiibo will generate a random mii for the file name in the JSON"

**Comment by XorTroll** [comment]
It's not supported yet (emuiibo currently only works with games)
