### ISSUE TITLE
Conflicting UUIDs

### ISSUE THREAD

**Issue by JStein01** [XorTroll/emuiibo#198]
First, I would like to say that I love your tool and appreciate the hours upon hours of hard work that must have been placed in this project.

When selecting the "generate all" option in Emutool some of the amiibos generated share UUIDs. This causes problems in BOTW for example where an amiibo is logged as already used for the day even though it has not yet been scanned.

I hope this is an easy fix for you!

**Comment by urherenow** [comment]
There is also an option to randomize UUIDs iirc

**Comment by JStein01** [comment]
> There is also an option to randomize UUIDs iirc

Thx but that then causes issues with super smash bros

**Comment by JStein01** [comment]
> > There is also an option to randomize UUIDs iirc
> 
> Thx but that then causes issues with super smash bros

I would like to be able to generate all with a fixed but unique uuid

**Comment by XorTroll** [comment]
I could ensure that all the generated amiibos in "generate all" have non-repeated UUIDs, but then the issue might happen with already existing amiibos in the SD card where the UUID repeats... would be quite helpful to try to check/prevent this

**Comment by JStein01** [comment]
> I could ensure that all the generated amiibos in "generate all" have non-repeated UUIDs, but then the issue might happen with already existing amiibos in the SD card where the UUID repeats... would be quite helpful to try to check/prevent this

Thanks for your response! I don't know if this would work but maybe you could seed the uuids based on the system time and increment for each Amiibo if using the generate all option. That way you wouldn't have to check if the uuid conflicts with existing emuiibos. I hope I am making sense, apologies for the poor grammar.
