### ISSUE TITLE
[Improvement] Different light patern for different tasks

### ISSUE THREAD

**Issue by cucholix** [XorTroll/emuiibo#20]
For example one blink on the home button for emuiibo emulation ON, long blink for emulation off, 2 blinks for swapping amiibo.

Of course an example you could find a better pattern

**Comment by deurk** [comment]
Agreed. Would be very convenient. I'd personally go for:

- 2 blinks for emulation ON
- long blink for emulation OFF
- 3 blinks for emulation ONCE
- 1 blink for previous/next amiibo

**Comment by XorTroll** [comment]
Done for 0.3 rewrite, different patterns are used for turning on, off, and when cannot move to next amiibo.
