### ISSUE TITLE
Current game is not being intercepted

### ISSUE THREAD

**Issue by QZypher** [XorTroll/emuiibo#203]
I carefully followed the instructions on the usage wiki yet every time I open a game, even if I enable emuiibo first, the game isn't intercepted. I've tried it so far with Miitopia and Super Smash Bros. Ultimate and i genuinely do not know what i am doing wrong

**Comment by lookye** [comment]
Please join Xors [Discord](https://discord.gg/3KpFyaH) server for support. The github issue tracker is not a support board.

**Comment by QZypher** [comment]
> Please join Xors [Discord](https://discord.gg/3KpFyaH) server for support. The github issue tracker is not a support board.

hey! sorry about that, this is my first time using github in any sense. I didn't realize there was a discord, thank you and sorry for posting this in the wrong place lol
