### ISSUE TITLE
No amiibos show up in the overlay

### ISSUE THREAD

**Issue by gabriel-marinkovic** [XorTroll/emuiibo#205]
Sorry if this has been asked before, I couldn't find a previous issue that matches this exactly.

I have created an amiibo with `emutool`. I placed it in `sd:/emuiibo/amiibo/Quinn/<json+flag>`. When open the overlay I can nagivate into the `Quinn` folder but there are no amiibos in it to select. 

I also tried putting the files in `sd:/emuiibo/amiibo/ACNH/Quinn/<json+flag>` (in the case that categories were required). The issue persists, I can navigate inside both ACNH and Quinn folders, but there is nothing to be selected inside of them.

I am using the latest version of everything required:
- `emuiibo 0.6.4`
- `emutool 0.6.3`
- `Tesla-Menu 1.1.4`
- `nx-ovlloader 1.0.6`

Thanks in advance.

**Comment by XorTroll** [comment]
Mind sending the amiibo folder emutool created as a ZIP? Wonder if anything's wrong there

**Comment by gyy52380** [comment]
Sure, I set the target folder to `target_folder`, everything inside of it is generated by emutool:
[target_folder.zip](https://github.com/XorTroll/emuiibo/files/8216860/target_folder.zip)

**Comment by lookye** [comment]
You dont put your stuff in a folder called `target_folder`.

Please read the [docs](https://github.com/XorTroll/emuiibo/blob/master/Usage.md) how to set up emuiibo and the amiibos correctly.

**Comment by XorTroll** [comment]
Yeah the amiibo seems to be fine, are you sure everything is in the correct location?

**Comment by lookye** [comment]
Closed due to inactivty and the problem should be solved with a correct setup.
