### ISSUE TITLE
how to setup the json and flag file

### ISSUE THREAD

**Issue by cwz6h** [XorTroll/emuiibo#206]
i have no idea how to but i also want to know if the overlay supports bin files

**Comment by XorTroll** [comment]
Virtual amiibos are meant to be created with emutool, not manually (and if so, their format is documented well-enough)

**Comment by XorTroll** [comment]
Also, plain bin dump support will return in the next release

**Comment by impeeza** [comment]
RCMPick Lock now dump the amiibo keys so will be easy for everyone get the own keys to decrypt bin files.  thanks a lot for your work.

**Comment by XorTroll** [comment]
Yeah, next emuiibo release (current work) makes use of that to decrypt them
