### ISSUE TITLE
Emuiibo and Sysbot 

### ISSUE THREAD

**Issue by chimel23** [XorTroll/emuiibo#208]
Will you be working on an Emuiibo update for 14.0? Currently I had to remove it to stop it crashing my Switch since I run Sysbot for live inject

**Comment by lookye** [comment]
emuiibo works fine on latest firmware/atmosphere version. There is no update needed. If it crashes bc of Sysbot, the problem lies somewhere else.

**Comment by chimel23** [comment]
Ok. I did not have he latest version though so I’ll try a fresh install with it
