### ISSUE TITLE
Saving in Smash Ultimate

### ISSUE THREAD

**Issue by xPvtPancakes** [XorTroll/emuiibo#21]
When trying to save the amiibo, occasionally the game will say "The data on this amiibo may have been overwritten by another console. Unable to write on this amiibo." I am unable to determine when this error occurs, because it does not happen every time. I have attempted to shut off the service by doing the right click + down in between the first scan and saving scans with no success

**Comment by sorenbug** [comment]
@xPvtPancakes It happens to me once the system sleeps at all. Can you confirm?

**Comment by xPvtPancakes** [comment]
It was happening if I re-loaded the amiibo almost immediately after saving. Easy workaround was to wait a minute or two between saving and re-loading

**Comment by robloxOBCTBCBC** [comment]
Same thing. now i can't save my data to the amiibo. Using your workaround didn't work

**Comment by XorTroll** [comment]
never been able to confirm it, and no testers have reported this issue :P

**Comment by XorTroll** [comment]
Mind testing this for v0.5?

**Comment by sorenbug** [comment]
I haven't played Smash in a while. I'll test it tomorrow and let you know if I can reproduce this issue.

**Comment by sorenbug** [comment]
I haven't been able to reproduce any issues thus far.

**Comment by XorTroll** [comment]
Considering how old this issue is I'm going to close it, if anyone experiences this error again just open a new one
