### ISSUE TITLE
emuiibo doesn't seem to be present...

### ISSUE THREAD

**Issue by KanobeGH** [XorTroll/emuiibo#213]
Emuiibo 0.6.4 deosn't load properly on my switch and I get the message "emuiibo doesn't seem to be present..." in tesla.
According to sysmodules it is set to start on boot, but it is always toggle off. The issue persists after reinstalling both atmosphere and Emuiibo. I also tried installing 0.6.3, because that worked a few months ago, but there its the same problem with a different message.
System version: 14.1.1|AMS 1.3.2|E

**Comment by impeeza** [comment]
Support on gbatemp, discord or the readme.md

**Comment by yourboid** [comment]
![123](https://user-images.githubusercontent.com/105564423/168446199-68055067-996c-4921-b20c-20f6fa3ce402.jpg)

**Comment by dalokaVAl** [comment]
I had the same problem, restarting the switch did the trick.

**Comment by Steverebo** [comment]
I have come across the same issue did you ever resolve this

**Comment by impeeza** [comment]
yes, following the instructions on the readme at op.

**Comment by lookye** [comment]
User error. This can be closed as a correct setup wont cause this problems.

**Comment by rafanic** [comment]
Sorry, but I've redone the walkthrough many times and I still get the same error. I've read the readme a thousand times

**Comment by urherenow** [comment]
This isn’t a help forum, so either take it to Discord, or gbatemp, where you’ll likely find the files you need. You’re using an outdated tesla menu or maybe even ovlloader.
