### ISSUE TITLE
Problems with new Monster Hunter Rise Amiibos (Emutool)

### ISSUE THREAD

**Issue by Armi-Heavy** [XorTroll/emuiibo#215]
The problem is because the new palico amiibo (sunbreak) and the new palamute amiibo (sunbreak) has de same name like the standar palico and palamute amiibos, the problem is when use te option "Generate al amiibo at once" they are overwritted and only appear the new one (Sunbreak version)

in the file system structure use the same name folder the original amiibo and the sunbreak edition amiibo.

**Comment by JianYuhaha** [comment]
yes, I also find this problem.
