### ISSUE TITLE
Emuiibo incorrectly recognizing Splatoon 3 Inkling (Yellow) virtual amiibo

### ISSUE THREAD

**Issue by pyrocumulus0** [XorTroll/emuiibo#225]
I created an Inkling (Yellow) virtual amiibo, but it is being displayed in Splatoon 3 as the orange haired Inkling Girl amiibo.

**Comment by VGmaster670** [comment]
I'm having the same issue

**Comment by Korados** [comment]
I'm having the same problem. I downloaded the binary from multiple sources but the Inkling Girl is always the orange one. I hope that gets fixed soon.

**Comment by lookye** [comment]
You guys should try the latest dev version on Xors discord server. It should solve your problem.

**Comment by Korados** [comment]
Okay, I downloaded the newest dev build from the discord, generated the Inkling - Yellow amiibo again with emutool but when I'm in the game, I just get: "An error has occurred. Please try again.". I get this error message for all amiibos with the dev build. When I use 0.6.4, the Inkling Girl is orange although emutool shows "Inkling - Yellow" as the folder name. I noticed that the overlay screen showed "This amiibo has no areas.". I have no idea what that means but could this be the problem?

**Comment by jekkkk** [comment]
Same problem as Korados. Tried Splatoon 2 and the same thing (different wording).

**Comment by Korados** [comment]
Still no answer to this? When I download the amiibo with the Amiigo app, the Yellow Inkling still gets recognised as the orange one. Is there no solution to this?

**Comment by pyrocumulus0** [comment]
I got the dev build from the discord server (https://discord.gg/3KpFyaH) and it worked for me

**Comment by VGmaster670** [comment]
Can confirm dev build works for me

**Comment by Korados** [comment]
Well, it is still not working for me. Is the latest dev build from June 9 2022, or is there a newer one? I tried it on this one and it didn't work the last time I checked.

**Comment by lookye** [comment]
Issue is resolved.
