### ISSUE TITLE
Makefile issue executing cargo

### ISSUE THREAD

**Issue by urherenow** [XorTroll/emuiibo#230]
I was going to make a build using the latest libtesla, but cargo really doesn't like your makefile (on Ubuntu). It ends up with 

```
Updating unicode-ident v1.0.4 -> v1.0.6
error: no such command: `nx`

        Did you mean `b`?

```
I assume because of this:

`&& cargo nx build --release`

I can simply remove nx from the line, but then get stuck at:

updating git repository `https://github.com/aarch64-switch-rs/logpacket`
error: failed to run `rustc` to learn about target-specific information

I'll try with mingw64 in Msys2 instead and update (or delete) this issue. Just gotta get rust and cargo installed first...
EDIT: Same thing in MinGW64

**Comment by djskual** [comment]
had you installed cargo-nx?
[https://github.com/aarch64-switch-rs/cargo-nx](https://github.com/aarch64-switch-rs/cargo-nx)

**Comment by urherenow** [comment]
Lol... I just saw this reply after scratching my head over it for some time

First, I had to uninstall rust and get rustup installed. Then I followed from step 2 and 3 here: https://github.com/aarch64-switch-rs/setup-guide.

I'm good now and have built it with the required libtesla change.
