### ISSUE TITLE
issue building overlay from source

### ISSUE THREAD

**Issue by TheKidThatCodes** [XorTroll/emuiibo#233]
why does the makefile cause recursion and just create infinite build directories inside of themselves
`make build` does this

why does this makefile have to be infinitely recursive
```makefile
$(BUILD):
	[ -d $@ ] || mkdir -p $@
	$(MAKE) --no-print-directory -C $(BUILD) -f "had to fix the makefile a little because i had a ' in the path (im using mac) but this would just point back to itself"
	# $(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile
```
i had to edit a little bacause the oath contained a `'` but my edits are not the problem
why does it do this

**Comment by XorTroll** [comment]
Can you try cloning emuiibo and compiling again?
Also, you you should just run `make`
