### ISSUE TITLE
Is this program for cracked terminals only? Can I use this in an official switch game pad?

### ISSUE THREAD

**Issue by youthug** [XorTroll/emuiibo#234]

**Comment by XorTroll** [comment]
I don't really understand what you mean here

**Comment by youthug** [comment]
Sry for not having been clear. I mean, it is safe to use this prgm in my Switch? Will Nintendo ban my Switch or account for this trick?

**Comment by Masamune3210** [comment]
If you are asking if you need a modded switch to use this, the answer is yes. 

If you are asking if you can use this without getting banned, it's more complicated but the answer trends heavily towards no

**Comment by youthug** [comment]
Got it. Thx for the answer!
