### ISSUE TITLE
16.0.2 support

### ISSUE THREAD

**Issue by PowerMan2015** [XorTroll/emuiibo#235]
switch crash loading emuiibo overlay on 16.0.2 ams 1.5.2 thx

Error code 2168-0002
Program 420000000007E51A

**Comment by valkayrie** [comment]
same problem
error code 2001-0123
program 420000000007E51A
firmware 16.0.2 ams 1.5.2

**Comment by urherenow** [comment]
There is an entire thread on gbatemp covering this, along with builds of all of the required things. You can’t simply install a new emuiibo, your tesla menu also has to be compatible (which is what your error code is yelling about in the first place).
