### ISSUE TITLE
16.0.2 not supported ?

### ISSUE THREAD

**Issue by LayKii98** [XorTroll/emuiibo#236]
![344766214_995350741455509_4792352551219846502_n](https://user-images.githubusercontent.com/132520433/236062758-cd8e9d47-5a44-4896-85f9-01359f25665f.jpg)

I try to use the emuiibo application on my console, but when I try to do it, it crashes and this appears. Can someone help me, either by telling me if they are working on a new version, or what should I do?

**Comment by JieZhangCoder** [comment]
> ![344766214_995350741455509_4792352551219846502_n](https://user-images.githubusercontent.com/132520433/236062758-cd8e9d47-5a44-4896-85f9-01359f25665f.jpg)
> 
> I try to use the emuiibo application on my console, but when I try to do it, it crashes and this appears. Can someone help me, either by telling me if they are working on a new version, or what should I do?

Today，I also encountered this problem.

**Comment by urherenow** [comment]
First, read already existing issues, and even closed ones. Nothing is more annoying than answering the same thing over and over. Your error isn’t even about emuiibo, it’s about Tesla menu.

**Comment by JieZhangCoder** [comment]
> 

Thank you for your reply. But Tesla is fine when it run EdiZon. It is the problem of the lastest Telsa, you mean?

**Comment by lookye** [comment]
Latest release supports everything up to the latest firmware.

**Comment by newwaverap** [comment]
Does anyone have a solution? I am also getting a crash immediately after launching Emuiibo from the Tesla menu but Edizon runs fine.

**Comment by urherenow** [comment]
Yes. Download the latest release. 1.0.0.

**Comment by newwaverap** [comment]
Everything was downloaded yesterday when I attempted to run it. I grabbed the latest releases of Tesla, Edizon and Emuiibo
