### ISSUE TITLE
emuiibo 0.6.5 service not found

### ISSUE THREAD

**Issue by romaxaa** [XorTroll/emuiibo#237]
Hello friends. Faced one problem. Emuiibo writes that the service was not found. What could it be? Are there any ways to solve this problem? Atmosphere 16.0.2. emuibo 0.6.5. Waiting for an answer! 
![изображение](https://user-images.githubusercontent.com/132555755/236151270-dd43e382-4d3f-4d0b-a9b4-aa8f89da019b.png)

**Comment by JieZhangCoder** [comment]
> Hello friends. Faced one problem. Emuiibo writes that the service was not found. What could it be? Are there any ways to solve this problem? Atmosphere 16.0.2. emuibo 0.6.5. Waiting for an answer! ![изображение](https://user-images.githubusercontent.com/132555755/236151270-dd43e382-4d3f-4d0b-a9b4-aa8f89da019b.png)

Atmosphere 16.0.2. emuibo 0.6.5. what‘s you tesla version？

**Comment by romaxaa** [comment]
> > Hello friends. Faced one problem. Emuiibo writes that the service was not found. What could it be? Are there any ways to solve this problem? Atmosphere 16.0.2. emuibo 0.6.5. Waiting for an answer! ![изображение](https://user-images.githubusercontent.com/132555755/236151270-dd43e382-4d3f-4d0b-a9b4-aa8f89da019b.png)
> 
> Atmosphere 16.0.2. emuibo 0.6.5. what‘s you tesla version？

Tesla version v1.0.6

**Comment by romaxaa** [comment]
> > Hello friends. Faced one problem. Emuiibo writes that the service was not found. What could it be? Are there any ways to solve this problem? Atmosphere 16.0.2. emuibo 0.6.5. Waiting for an answer! ![изображение](https://user-images.githubusercontent.com/132555755/236151270-dd43e382-4d3f-4d0b-a9b4-aa8f89da019b.png)
> 
> Atmosphere 16.0.2. emuibo 0.6.5. what‘s you tesla version？

can you suggest something?

**Comment by lookye** [comment]
Just wait for a proper release which should come soon.

**Comment by romaxaa** [comment]
> Just wait for a proper release which should come soon.

Thanks you!

**Comment by JieZhangCoder** [comment]
My version has the same issue as you. 
https://github.com/WerWolv/Tesla-Menu/issues/63#issue-1695590670

**Comment by romaxaa** [comment]
> My version has the same issue as you.

I'm sorry that you're having the same problem as me. But thanks anyway!

**Comment by urherenow** [comment]
https://gbatemp.net/threads/emuiibo-0-6-5-doesnt-seem-to-be-present.632131/post-10145187

Looks like none of the recent releases are here on the github, so this really is a bug. If you learn to compile your own stuff, you only need to clone this repo and build it with the LATEST libtesla, and LATEST libnx. The post I linked for you had a build.

**Comment by lookye** [comment]
Use the latest release and set it up correctly.
