### ISSUE TITLE
Emuiibo Crashing on Atmosphere 16.0.2

### ISSUE THREAD

**Issue by newwaverap** [XorTroll/emuiibo#241]
Hello, Emuiibo is crashing immediately after launching from the Tesla menu but edizon works fine from Tesla I’m on firmware 16.0.2 running the latest atmosphere

**Comment by lookye** [comment]
Make sure your files are completely up to date. So tesla files (in atmosphere/contents AND switch/.overlays) as well as all emuiibo files in the same directories. Also make sure your amiibos are generated freshly to be sure that they wont produce eny problems.

**Comment by lookye** [comment]
After testing myself in docked and handheld mode. It does not crash.
