### ISSUE TITLE
Tesla overlay menu is empty and displays `???`

### ISSUE THREAD

**Issue by Avasam** [XorTroll/emuiibo#247]
The emuiibo page in the tesla menu overlay is empty. It just says:
```
Emuiibo
???

-------

```

I have installed the Tesla Menu, nx-ovlloader and emuiibo from the HB App Store.

System: 15.0.1 | AMS 1.4.0 | S

**Comment by lookye** [comment]
Your files are not up to date. Read the readme and update all files from tesla and emuiibo manually.

**Comment by impeeza** [comment]
the HB App Store is not updated, update all your files manually from their own repos.
