### ISSUE TITLE
Generated long names amiibos 

### ISSUE THREAD

**Issue by impeeza** [XorTroll/emuiibo#249]
Hi, thanks a lot for your work.

On the latest release note you can read:

> Now virtual amiibos with names longer than 10 characters are ignored and considered as invalid. Due to certain technical reasons (and Nintendo being too inconsistent with its formats) I originally thought the limit was at 40, but in certain contexts (like system settings) where the 10-char limit is imposed, existing virtual amiibos with longer names tend to cause weird/unexpected behavior.

The EmuTool companion tool generate the emuiibos as indicated by amiiboapi; which have names longer than 10 characters.  What will happen to those amiibos generated?

**Comment by XorTroll** [comment]
emuiibo will automatically truncate those names, but emutool did generate long ones :P
Last commit fixes this

**Comment by impeeza** [comment]
Thank you buddy, regards

**Comment by impeeza** [comment]
Hello @XorTroll I just downloaded latest EmuTool generated by Workflow, when you generate a new Amiibo they name is trimmed to 10 chars long, but when you generate all amiibos at once the long AmiiboAPI names are kept.
