### ISSUE TITLE
V.02 doesn't work with atmosphere 0.8.10 and nand 8.0.1

### ISSUE THREAD

**Issue by KernelGM** [XorTroll/emuiibo#25]
I'm using version 0.2 of emuiibo and it does not work with atmosphere 0.8.10. Can someone help me?
Obs: I put all .bin in the :\emuiibo\ folder. But when I try to use pressing the right d'pad +up arrow does not work. With AmiiSwap sometimes works if I enable before starting the game, but I can not change amiibo during the game with dpad right + right arrow.

**Comment by XorTroll** [comment]
The version, not emuiibo nor atmos's one, should be a problem. I am with latest atmos, emuiibo and firmware (so the same as you) and emuiibo is fine there.

Are you talking about BotW, specifically?

**Comment by KernelGM** [comment]
> The version, not emuiibo nor atmos's one, should be a problem. I am with latest atmos, emuiibo and firmware (so the same as you) and emuiibo is fine there.
> 
> Are you talking about BotW, specifically?

Yes sir. Exactly with BotW.

**Comment by XorTroll** [comment]
BotW is certainly "special", and since it accesses Amiibo stuff as soon as it's launched, emuiibo needs to be toggled before the game is even launched (I know, it's an special case, not emuiibo's problem)

**Comment by KernelGM** [comment]
> BotW is certainly "special", and since it accesses Amiibo stuff as soon as it's launched, emuiibo needs to be toggled before the game is even launched (I know, it's an special case, not emuiibo's problem)

Have one option to toggle .bin without AmiiSwap?
