### ISSUE TITLE
Emuiibo doesn't seem to be present

### ISSUE THREAD

**Issue by AnthonieZ87** [XorTroll/emuiibo#254]
When I open the overlay this appears  under bigger brighter text in smaller grey text
"Emuiibo doesn't seem to be present"
I am new to emuiibo so now sure what I am doing wrong

**Comment by lookye** [comment]
You did not completely set up emuiibo correctly. Please read the readme.

**Comment by rafanic** [comment]
I do everything right, but hd the same message

**Comment by lookye** [comment]
Then join discord (its linked on top in the readme) for further support.
