### ISSUE TITLE
emuiibo doesn't seem to be present

### ISSUE THREAD

**Issue by pokemonfan6498** [XorTroll/emuiibo#258]
i done everything like instructions said but i still get emuiibo doesn't seem to be present even when having virtual amiibos

**Comment by lookye** [comment]
You did not as instructed in the readme. Please set it up correctly.

**Comment by pokemonfan6498** [comment]
but i cannot even enable it in sys modules

**Comment by lookye** [comment]
It works fine if you exactly set it up as explained in the readme. If you need further help to do so, please use the discord server which is linked in the top of the readme.
