### ISSUE TITLE
emuiibo doesn't work with Zelda Skyward Sword 

### ISSUE THREAD

**Issue by flopinou** [XorTroll/emuiibo#259]
Even when launching the emulation before launching the game, the game is marked as "not intercepted" and the amiibo doesn't work.

**Comment by lookye** [comment]
Did you try to use an amiibo via emuiibo ingame? "Not Intercepted" changes in some games, when the ingame amiibo menu opens.

**Comment by flopinou** [comment]
Oh yes it works, thank you very much!
