### ISSUE TITLE
[Rquest] Add compatibility for Switch 8.1.0 fw

### ISSUE THREAD

**Issue by cucholix** [XorTroll/emuiibo#26]
Current emuiibo 0.2 module doesn't allow atmosphere 9.0.1 to boot normally, you need delete emuiibo folder in titles or else atmosphere get stuck in Nintendo Switch logo.

**Comment by mrdude2478** [comment]
Same issue here - once I deleted emuiibo folder from Atmosphere/titles. Then 8.1.0 firmware would boot up just fine. Hopefully this is simple to fix.
