### ISSUE TITLE
Mii error on setting and decrypting.

### ISSUE THREAD

**Issue by impeeza** [XorTroll/emuiibo#261]
Hello there, first thanks a lot for all your effort and great work.

I am using a Erista V1 unpatched console, with the next software:
- Atmosphère	1.5.4
- Hekate		6.0.5
- Firmware	16.0.3 Rebootless Update # 2
- Emuiibo		1.0.0 commit a7177e1 (also tested on 97326a0 and 704380d)

Well, the steps to reproduce the problem are:

On my New Nintendo 3DS XL Firmare 11.16.0.4-49U using HOME Menu -> amiibo Settings Register Owner, Nickname and Mii on a physical Amiibo (NFC tag):

![image](https://github.com/XorTroll/emuiibo/assets/41979604/12bed005-a508-4796-bb72-1622fa6ce841)

After that on the same New Nintendo 3DS XL using the Thenaya homebrew, dump the NFC tag to the 040655DF6EAF61_203306291648.bin file (572 bytes):

![image](https://github.com/XorTroll/emuiibo/assets/41979604/5ebfa1a8-a324-4ef0-ad05-fb3286fe95b3)

Copy the 040655DF6EAF61_203306291648.bin file to the SD:/emuiibo/amiibo/ folder on my Nintendo Switch Console.

![image](https://github.com/XorTroll/emuiibo/assets/41979604/1c8c9433-383a-4f9a-8e46-00ad571ca153)

Restart the console, after the restart the SD:/emuiibo/amiibo/ folder now have a 040655DF6EAF61_203306291648 folder with the NFC dumped amiibo files on it:

![image](https://github.com/XorTroll/emuiibo/assets/41979604/9d8a9ff5-a5c1-4bcb-8f43-907b85d2e8c1)

![image](https://github.com/XorTroll/emuiibo/assets/41979604/70ae4c18-b755-476f-95aa-6f7465e080f3)

Now setting emuiibo trough the OVL to use the new amiibo then go to Settings -> amiibo -> Register Owner and Nickname then "connect" the emuiibo's amiibo:

![image](https://github.com/XorTroll/emuiibo/assets/41979604/db7f78e3-34e4-490d-a634-7e034f6ffd3a)

As you can see the Owner and the Mii are incorrect, but the Nickname is correct.

![image](https://github.com/XorTroll/emuiibo/assets/41979604/25c1a81a-1f53-432e-aa4c-90f69ec6899e)

if you look on the recently created amiibo folder the mii-charinfo.bin file contains:

![image](https://github.com/XorTroll/emuiibo/assets/41979604/5db43595-c493-42bf-91b0-89569dc43091)

Now using Switch Settings, change the Owner and Mii for the emuiibo's amiibo:

![image](https://github.com/XorTroll/emuiibo/assets/41979604/0fa80217-87e1-48b2-8bf1-de8c62169bf4)

![image](https://github.com/XorTroll/emuiibo/assets/41979604/5d2c7884-394e-462c-a141-c7f011cb1bec)

After that, "disconnect" the emuiibo's amiibo and test the new settings, going again to Settings -> amiibo -> Register Owner and Nickname; and then "connect" the emuiibo's amiibo:

![image](https://github.com/XorTroll/emuiibo/assets/41979604/be5a565c-000f-4c88-b542-e1d5d5019816)

![image](https://github.com/XorTroll/emuiibo/assets/41979604/e4038a45-d65d-437f-912d-52157a4562aa)

As can see on the next image, the Owner name is correct, but the Mii have a minor change:

![image](https://github.com/XorTroll/emuiibo/assets/41979604/8c40830e-681d-4f03-8f73-2f5f15d8ea62)

The original set up Mii vs the actual Mii:

![image](https://github.com/XorTroll/emuiibo/assets/41979604/258258ee-9436-46c9-a9f8-c1b01d8ddc66)

Comparison between the mii-charinfo.bin on the emuiibo's amiibo folder (SD:/emuiibo/amiibo/040655DF6EAF61_203306291648) left and the corresponding mii-charinfo.bin on SD:/emuiibo/miis/2/ folder dumped by the same emuiibo (I did that file compared with other miis dumped by other tools and are the same)

![image](https://github.com/XorTroll/emuiibo/assets/41979604/72c1f039-0d23-490c-8d36-a05e9e935ff6)

As you can see the processed mii-charinfo.bin by emuiibo when using settings applet, differs from the one dumped by emuiibo from console.

If I do replace the mii-charinfo.bin whit the one dumped the amiibo have the correct Mii.

For summary, seems there are two problems:

- When converting a binary dump from Thenaya (572 bytes) the Owner information is missed.
- When emuiibo MITM the settings applet the Mii information is changed.

Hope has been clear, let me know if I can do more testing.

Obviously I don't put here the binary files but if you need them, I can share with you.

Regards from Colombia

**Comment by XorTroll** [comment]
Thanks for such a detailed issue ;)
Could you contact me in Discord so we can discuss this more directly?

**Comment by impeeza** [comment]
Normally I do not use discord but no problem will try to get you there 😁

**Comment by XorTroll** [comment]
Last commit fixes the 2nd issue, it was a typo I made with mii type conversions in the Rust nx libs
The other one is going to be tougher too look into

**Comment by impeeza** [comment]
Hello there,  Just updated to Emuiibo 1.1.0 and the second error, activating a Amiibo, going to Settings->amiibo->Register Owner and Nickname the mii avatar still wrong.

regards

**Comment by impeeza** [comment]
Thanks a lot for all your help. Closing the Issue.
