### ISSUE TITLE
Wont set up

### ISSUE THREAD

**Issue by Blacknife420** [XorTroll/emuiibo#267]
Are you going to keep updating emutool as it won't set up

**Comment by XorTroll** [comment]
What issue do you have with emuiigen

**Comment by Blacknife420** [comment]
It won't let get it running at all

**Comment by urherenow** [comment]
Install Java.

**Comment by Blacknife420** [comment]
Already have java fixed the issue I was having tho

**Comment by lookye** [comment]
So, your problem is solved?

**Comment by Blacknife420** [comment]
Yes I manged to fix the issue don't ask how I have no idea
