### ISSUE TITLE
Trouble correctly identifying some amiibo

### ISSUE THREAD

**Issue by ashamefuldog** [XorTroll/emuiibo#29]
Specifically the wedding versions of Bowser/Mario/Peach, and gold version of Mario, get recognized as their normal versions when trying to unlock stuff in Mario Odyssey (attempted with quite a few different dumps)

**Comment by dbenoy** [comment]
I'm experiencing this same problem.

8.1.0 (AMS 0.9.1) + emuMMC

**Comment by vanyasem** [comment]
Still a thing on latest version

**Comment by XorTroll** [comment]
Fixed for the next version :)
