### ISSUE TITLE
Writing Data to Amiibo/Emuiibo

### ISSUE THREAD

**Issue by Cakedy** [XorTroll/emuiibo#3]
Would writing data to an amiibo be a planned feature later on? Otherwise, whenever you rescan/re-emulate the amiibo, like in Super Smash Bros Ultimate, it picks it up as a new amiibo rather than a previously saved amiibo.

**Comment by XorTroll** [comment]
Already done locally, going to commit in a few mins, will be on 0.2. Amiibo progress is saved locally in files, but writing to real amiibos is still something to work on.
