### ISSUE TITLE
emuiibo crashes on 8.1.0

### ISSUE THREAD

**Issue by j-james** [XorTroll/emuiibo#32]
Copy-pasting from [my Atmosphere issue](https://github.com/Atmosphere-NX/Atmosphere/issues/627)

It crashes all of Atmosphere upon activating, and it's Atmosphere-independent (SciresM)

### What's the issue you encountered?

Atmosphère crashed.

### How can the issue be reproduced?

It can be reproduced by going to sdsetup.com](https://www.sdsetup.com/console?switch) and selecting the same packages, then turning on emuiibo, sys-ftpd, and sys-clk and rebooting into CFW.

### Crash Report

I have two crash reports, one after booting from fusee-primary and the other after booting from hekate. [Gist](https://gist.github.com/j-james/ec1a7b6b13f9ad1c207557bd8d5e76b7)

### System Firmware Version

8.1.0

### Environment?

I launched Atmosphère by fusèe first, then hekate.\
I used Kosmos's (13.0.1) latest build of Atmosphère (0.9.2).

sysmodules:
- emuiibo
- hid-mitm
- sys-clk
- sys-ftpd
- sys-netcheat
- ldn_mitm

homebrew:
- Kosmos Updater
- Kosmos Toolbox
- AmiiSwap
- Checkpoint
- Goldleaf
- NxThemes Installer
- Retroarch
- MelonDS

### Additional context?
I activated emuiibo, sys-clk, and sys-ftpd before the error.\
I'd guess that this is an emuiibo issue. 

![Screenshot_20190708-150938_Camera](https://user-images.githubusercontent.com/35242550/60846925-e07d0700-a195-11e9-9fb6-57836f0f7464.jpg)

**Comment by thunder-17** [comment]
Try to make on you sd card alredy a emuiibo folder

**Comment by thunder-17** [comment]
SDROOT/emuiibo

**Comment by lookye** [comment]
If you have too much sysmodules enabled, your system cant boot and will crash.
Disable some sysmodules and emuiibo will work as intended.

It happens as the system has not enough RAM for everything to load.
