### ISSUE TITLE
Not Working on 8.1.0

### ISSUE THREAD

**Issue by Sevyn13** [XorTroll/emuiibo#33]
Running Kosmos v13.0.1 w/ Atmosphere 0.9.2 on 8.1.0. When I drop the 0100000000000352 folder in to my atmosphere/titles folder I begin to have problems. On emuiibo v0.2.0 when booting I get stuck at the Nintendo Switch logo and have to hold the power button to restart. When I use emuiibo v0.2.1 I can boot but when I launch The Homebrew Launcher it crashes and I have to reboot.

**Comment by lookye** [comment]
#32 Please read my comment in this issue.

**Comment by XorTroll** [comment]
Already answered. Too many sysmodules won't boot fine.
