### ISSUE TITLE
Always No controller which supports NFC was found

### ISSUE THREAD

**Issue by iEldik3** [XorTroll/emuiibo#36]
When i try use emuiibo in smash it say "No controller which supports NFC was found" ALWAYS.No matter what amiibo i use.

**Comment by lookye** [comment]
Giving more information like:

CFW?
Firmware?
emuiibo version?

Did you enable emuiibo before starting the game with R3 + dpad_up?
Are the amiibos compatible with the [game](https://www.nintendo.com/amiibo/compatibility/#compatible/game/ff81fad6-cc05-3cfc-8684-e656b317328f)?

**Comment by rgarcia7** [comment]
Hi, I have the same error, on smash "No controller which supports NFC was found", and no response from other games
My system is a switch version 8.0.1

A little context, A week ago I was using firmware Atmosphere 13.0.1 with emuiibo  0.2.1 and Amiiswap 1.0, with this configuration everything worked perfect, I was using exfat. Was using this config for like a month with no issues.

- I could enable and disable emuiibo from Amiiswap
- I was able to use amiibos in any games, including smash
- Saving data to amiibos in smash worked

This last weekend I updated to Atmosphere 13.2 with emuiibo 0.3 and same Amiiswap version and wanted to configure fat32 in the sd card, to avoid having issues I backed my save files in my computer, wiped the sd card, and started from scratch setting the sdcard with the new CFW.

The first thing I noticed is that when going to Amiiswap after enabling emuiibo and restarting, is that when I enabled emuiibo there, it said Emuiibo **state is unknow**, and there was no amiibo listed either
When going to NX-Shell and checking /root/emuiibo/amiibo/, the folders where created by emuiibo but empty

So I tried to enable it with the command DPad Up and Right Tumbstick, I got the blue indicator.
When I checked the status with Amiiswap still said state is unknown.

**Comment by rgarcia7** [comment]
Hi, I have the same error, on smash "No controller which supports NFC was found", and no response from other games
My system is a switch version 8.0.1

A little context, A week ago I was using firmware Atlas NX Kosmos 13.0.1 with Atmosphere 0.9.2, using emuiibo 0.2.1 and Amiiswap 1.0, with this configuration everything worked perfect, I was using exfat. Was using this config for like a month with no issues.

I could enable and disable emuiibo from Amiiswap
I was able to use amiibos in any games, including smash
Saving data to amiibos in smash worked
This last weekend I updated to Atlas NX Kosmos 13.2 with Atmosphere 0.9.3, using emuiibo 0.3 and same Amiiswap version and wanted to configure fat32 in the sd card, to avoid having issues I backed my save files in my computer, wiped the sd card, and started from scratch setting the sdcard with the new CFW.

The first thing I noticed when going to Amiiswap after enabling emuiibo and restarting, is that when I enabled emuiibo there, it said Emuiibo state is unknow, and there was no amiibo listed either
When going to NX-Shell and checking /root/emuiibo/amiibo/, the folders where created by emuiibo but empty

So I tried to enable it with the command DPad Up and Right Tumbstick, I got the blue indicator.
When I checked the status with Amiiswap still said state is unknown.

**Comment by lookye** [comment]
It is related to #39 .
Maybe you should read my comment there. If you set up emuiibo correctly (read Readme for reference) you can use it just fine as intended.
Also Amiiswap needs to be updated and you should make an issue at its Git for that.

**Comment by rgarcia7** [comment]
Ok, I will check the Readme and for people having this issue, I found this post https://www.homebrewgeneral.net/2019/08/emuiibo-v03-released.html

Thanks
