### ISSUE TITLE
Can't switch between amiibo

### ISSUE THREAD

**Issue by nightshade1121** [XorTroll/emuiibo#38]
I have my folders set up correctly and everything but the shortcut to switch to the next amiibo (R thumb click + left D pad) refuses to work. The home button lights up but they don't swap. I've also checked to make sure both amiibo work perfectly, the folders have their JSONs inside and everything and only work if only one is in the emuiibo folder at a time.

I'm using emuiibo v.03
I have atmosphere 0.9.2
I'm trying to swap between two amiibo, a Ike and a Isabelle, from smash bros.

In and out of the game, they won't swap but only work if they're the only amiibo folder in the emuiibo folder.

**Comment by This-will-be-your-username** [comment]
I've only just started using emuiibo, however testing 0.3 and 0.3.1 new amiibos are only recognized after rebooting the switch.

If you've added new amiibos, reboot, then reactivate emuiibo. You should be able to then swap to any new amiibos added.

**Comment by XorTroll** [comment]
^ and maybe try latest version...?
