### ISSUE TITLE
8.1 system + 0.93 atmosphere could not used

### ISSUE THREAD

**Issue by shallwei** [XorTroll/emuiibo#39]
Swithch 8.1（no fake system）+ Atomsphere 0.93
Amiiswap 1.0 + Emuiibo 0.21
In Amiiswap could load the Amiibo.bin and enable Emuiibo(the green lignt up)
In Zelda could not use and press the ==> + R-stick no feedback. the home button blue light up mean it could use.
and use the Emuiibo 0.3 could not load the amiibo.bin in Amiiswap.(0.21 could load)

**Comment by lookye** [comment]
1. Amiiswap may needs to be updated from its dev.
2. There is no emuiibo 0.23 only 0.2, 0.21 and 0.3
3. If you have problems with amiiswap not choosing the amiibos correctly, please make an issue on its github repo, so the dev can update it to work with emuiibo 0.3.

**Comment by sw3d3r** [comment]
same issue here , its not a problem with amiiswap its emuiibo is not finishing the amiibo emulation, i have tried both versions of emuiibo on atmosphere 0.9.3 and they do not emulate the amiibo, as well i have tried amiiswap with emuiibo 0.2.1 and amiiswap recognizes emuiibo as active and also the amiibo chosen but in game emuiibo is not emulating anything, i have determines that emuiibo is not running properly on atmosphere 0.9.3 running fw 8.1.0
