### ISSUE TITLE
Use DKP libnx instead of a local one

### ISSUE THREAD

**Issue by sorenbug** [XorTroll/emuiibo#4]
The `make`file uses `./libnx-master/nx` as the `libnx` dir, while it should use `$DEVKITPRO/libnx`. Symlinking the two directories allows the project to build appropriately.

**Comment by Ch0cola** [comment]
The $DEVKITPRO/libnx isn't updated, I think he download the current master intentionally to support the v8.0.0

**Comment by sorenbug** [comment]
I just built with DKP libnx. It works fine on 8.0.0.
