### ISSUE TITLE
Algunos dumps no funcionan en BOTW

### ISSUE THREAD

**Issue by usuario593** [XorTroll/emuiibo#40]
Algunos dumps de BOTW solo arrojan pescados y cofres aleatorios, y no dan los objetos que deberia

**Comment by tralyaeternus** [comment]
Actualicé a la versión 0.3 de emuiibo y este problema persiste, incluso utilizando emuGUIibo para generar los amiibos en lugar de usar dumps.

**Comment by fau-fau** [comment]
still having no sucess on 0.4

**Comment by XorTroll** [comment]
#30 duplicate
