### ISSUE TITLE
Unable to download Amiibos from API

### ISSUE THREAD

**Issue by stvene3004** [XorTroll/emuiibo#42]
as you can tell from the title, My emGUIiibo told me that it can't download the amiibos from the API. Is there ANY way to fix this?

**Comment by stef157** [comment]
Same for me…

**Comment by BaconBurrtango** [comment]
Having this issue as well, it works fine on my desktop but throws this error on my laptop. Both are on the same network so not sure why one can connect fine and the other can't

**Comment by leo60228** [comment]
This happened to me, just try running it again. I think the API is super slow or something.

**Comment by XorTroll** [comment]
#69 moving here, duplicate
