### ISSUE TITLE
Causes 2168-0002 error on 9.0.0, AMS 0.9.4

### ISSUE THREAD

**Issue by d4mation** [XorTroll/emuiibo#43]
Fatal crash on boot until I deleted Emuiibo manually from my SD card.

Booting with plain ol' fusee-primary. Nothing special about my setup; I've only used Checkpoint and Emuiibo on my Switch.

**Comment by XorTroll** [comment]
Emuiibo needs a new release every new version. Will make one soon, don't worry!

**Comment by d4mation** [comment]
I figured, especially with it being a Major version bump from Nintendo. I was more logging it here to help others who may be confused :)

**Comment by XorTroll** [comment]
0.3.1 fixes this.

**Comment by DitDitGitHub** [comment]
I'm still getting this issue.
