### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by mrdude2478** [XorTroll/emuiibo#44]
In the new emuGUIibo, when you select an amiibo the picture of the amiibo is displayed, when you generate the virtual amiibo would it be possible to also save the image file as amiibo.icon in the same folder where the json files get generated.

Just need to add a second checkbox and add this code:

if (checkBox2.Checked)
                    {
                        pictureBox1.Image.Save(Path.Combine(amiiboDir, "amiibo.icon"));
                    }

Thanks.

**Comment by DarkWolfInsanity** [comment]
I actually have a better method of this. If its possible to hook into the console's notification system (battery low, friend online, etc), add a function to it that states which amiibo is active when you perform the button combos.

**Comment by XorTroll** [comment]
Alreasy considered it, notifications don't work as simple as that, and it wouldn't be possible to use custom ones.

**Comment by mrdude2478** [comment]
@XorTroll
I already modded it to download icons, and posted it here:
https://gbatemp.net/threads/modded-emuguiibo.548485/#post-8799502

I hope you can add this mod to your future updates, but if not - no worries, thanks anyway.

**Comment by XorTroll** [comment]
Next version's emutool will allow saving the icon as a PNG file
