### ISSUE TITLE
Button combo R3+dpad does nothing.

### ISSUE THREAD

**Issue by Kyamon** [XorTroll/emuiibo#45]
In TLoZ: BotW, instead of amiibo items spawning it just goes to the menu or sheika slate scope depending on what button was pressed first.
Using 0.3.1 with a combination of bin dumps and generated with emuGUIibo.
There are also PNG files in the amiibo folder.

**Comment by lookye** [comment]
You need to enable the amiibo feature and then select it in the short menu (where the bomb, magnet and stuff is). When you enable emuiibo before starting the game and activate an amiibo, it works as intended. The "bug" you mention is normal ingame behavior bc of the buttons you need to press (e.g. R3).

**Comment by Kyamon** [comment]
I have amiibo feature in-game enabled and am using the rune... obviously...

**Comment by lookye** [comment]
Tbh, that wasnt clear in how you described it.

So, wenn you enable emuiibo, then start the game, then choose the amiibo rune and press R1 or what it was to enable the rune it opens the menu or something else?

**Comment by Kyamon** [comment]
Boot into CFW -> open hbmenu -> open kosmos toolbox -> background modules -> emuiibo is on -> back out to home menu -> open BotW -> use amiibo rune -> press R3+dpad -> 
![image](https://user-images.githubusercontent.com/15200348/65393425-a9060b80-dd3d-11e9-81a4-68b2180b8fbd.png) or 
![image](https://user-images.githubusercontent.com/15200348/65393431-b9b68180-dd3d-11e9-82e7-07edf677516a.png) appears.

Cannot get amiibo items to spawn.

**Comment by lookye** [comment]
You need to enable emuiibo with r3 + dpad up before starting the game. Then, if you enable the amiibo rune and use it (like the bombs or ice blocks) the items will spawn.

**Comment by Kyamon** [comment]
Backed out to home menu, closed the game completely. Did the dpad down then up combos and got meat in-game. Getting somewhere...
Tried backing out to home menu and doing dpad right to switch amiibos, rune says I can't use this amiibo again today back in-game. Okay, so closed game completely again, did dpad combos down up then right, nothing in-game again.

**Comment by abccsr** [comment]
> Backed out to home menu, closed the game completely. Did the dpad down then up combos and got meat in-game. Getting somewhere...
> Tried backing out to home menu and doing dpad right to switch amiibos, rune says I can't use this amiibo again today back in-game. Okay, so closed game completely again, did dpad combos down up then right before starting up the game, nothing in-game again.

have u solve the problem ? if not , i will tell you

**Comment by kojuki** [comment]
> > Backed out to home menu, closed the game completely. Did the dpad down then up combos and got meat in-game. Getting somewhere...
> > Tried backing out to home menu and doing dpad right to switch amiibos, rune says I can't use this amiibo again today back in-game. Okay, so closed game completely again, did dpad combos down up then right before starting up the game, nothing in-game again.
> 
> have u solve the problem ? if not , i will tell you

Man, why just don’t tell the solution if you have it? Okay, topicstarter did not reply. Could you please give advice to me? Same problem here. With latest atmosphere and kefir.

**Comment by Kyamon** [comment]
> have u solve the problem ? if not , i will tell you

Haven't messed with it since I last posted here, so no I haven't solved the problem... What's the point of posting if you aren't going to even share the solution in the first place?

**Comment by akmkaio** [comment]
If you also have this issue, try going to /emuiibo/settings.json and changing "comboEnabled": false to true. It worked for me at least. GL

**Comment by kojuki** [comment]
> If you also have this issue, try going to /emuiibo/settings.json and changing "comboEnabled": false to true. It worked for me at least. GL

Thank you. After doing so my switch did not start. To solve I need to eject memory card, insert it to pc, edit file back, than it would start as usual

**Comment by akmkaio** [comment]
> > If you also have this issue, try going to /emuiibo/settings.json and changing "comboEnabled": false to true. It worked for me at least. GL
> 
> Thank you. After doing so my switch did not start. To solve I need to eject memory card, insert it to pc, edit file back, than it would start as usual

Well, tbh I dont see how the two could be related, since that json doesnt have any other info. But, good thing you reported a fail, as I said, it worked perfectly in my system (I'm on latest Atmosphere, Latest Hekate, and SD is formatted as FAT32) .

**Comment by kojuki** [comment]
> > > If you also have this issue, try going to /emuiibo/settings.json and changing "comboEnabled": false to true. It worked for me at least. GL
> > 
> > 
> > Thank you. After doing so my switch did not start. To solve I need to eject memory card, insert it to pc, edit file back, than it would start as usual
> 
> Well, tbh I dont see how the two could be related, since that json doesnt have any other info. But, good thing you reported a fail, as I said, it worked perfectly on my system (I'm on latest Atmosphere, Latest Hekate, and SD is formatted as FAT32) .

I also at the latest atmosphere + hekate + kefir + fat32.  And for me - I do not see how it could be related, but as fact. And I m not the only one with same behavior. Some users reports it works fine and some - have same issue as I have.

**Comment by kojuki** [comment]
> > > If you also have this issue, try going to /emuiibo/settings.json and changing "comboEnabled": false to true. It worked for me at least. GL
> > 
> > 
> > Thank you. After doing so my switch did not start. To solve I need to eject memory card, insert it to pc, edit file back, than it would start as usual
> 
> Well, tbh I dont see how the two could be related, since that json doesnt have any other info. But, good thing you reported a fail, as I said, it worked perfectly on my system (I'm on latest Atmosphere, Latest Hekate, and SD is formatted as FAT32) .

Could you write your home brew list? May be some of it would help :)

**Comment by lookye** [comment]
Homebrews (maybe sysmodules) wont affect that behavior. 
I tested emuiibo on FW9.2. + latest AMS. Everything works as intended. I also set the settings.json entry to "true". Enabling/Disabling/Choosing an amiibo works fine with the button combos or via latest Goldleaf just fine.

**Comment by urherenow** [comment]
Maybe it’s the program being used to edit the .json file. DOS vs Unix line endings and such...
