### ISSUE TITLE
Using amiibos on Link's awakening hangs the game

### ISSUE THREAD

**Issue by trueicecold** [XorTroll/emuiibo#48]
I've got some amiibos created with the GUI tool (4 json file in each folder)
When trying to use it in Link's awakening it's not detected, and pressing "Quit" in the game hangs it.

I do see the light in the home button turn on when clicking the r-stick and up dpad

I'm using emuiibo 0.3.1, fw 8.1.0

**Comment by CecilFF4** [comment]
This is the only game I want to use amiibo with... and they just don't work. I see the same as you and have the same versions.

**Comment by severinkaderli** [comment]
Can confirm that it's still not working in Link's Awakening as of emuiibo 0.4.0 but it's working in other games.

**Comment by impeeza** [comment]
Any news on this issue. I did think was only me. But working well on others titles

**Comment by XorTroll** [comment]
Fixed for the next version :)

**Comment by impeeza** [comment]
Cool. Thanks a lot

**Comment by ddubs13** [comment]
I'd like to bump this by saying it's not working in Link's Awakening for me at all.
