### ISSUE TITLE
Amiibos keep Switching 

### ISSUE THREAD

**Issue by Jackall4BDN** [XorTroll/emuiibo#49]
When i activate emulation, ingame it seems like it just does nothing,
when i then pop up amiiswap, it states emuiibo status to be unknown while constantly switching rapidly between my amiibos thus not staying on long enough to be registered by games, i assume.
Is there anything wrong with my setup or a way to avoid that or is this a common bug?

**Comment by An70ni092** [comment]
AmiiSwap does not work with the latest version of emuiibo.
However, there are also problems using emuiibo alone.
I wait for an answer [here](https://github.com/XorTroll/emuiibo/issues/47)

**Comment by XorTroll** [comment]
^
