### ISSUE TITLE
Possible SX OS version? 

### ISSUE THREAD

**Issue by rjurok16** [XorTroll/emuiibo#5]
Any possibilities that you will release an NSP  or NRO version of this?

**Comment by Ch0cola** [comment]
It's a background service patch, can't be packed on NSP or NRO...

You can use it with another CFW, SX OS didn't allow this patches.

**Comment by rjurok16** [comment]
I see. Thank you so much!

**Comment by XorTroll** [comment]
SX OS's problem.
