### ISSUE TITLE
Latest Kosmos/Atmosphere crashes on boot when using emuiibo 0.3.1 on FW 9.0.0

### ISSUE THREAD

**Issue by Flocki1987** [XorTroll/emuiibo#50]
![IMG_1927](https://user-images.githubusercontent.com/55653726/65491865-2f425f00-deb0-11e9-931f-dd1b4a8cee6a.jpg)

When using the latest emuiibo I received the attached error.

**Comment by lookye** [comment]
Disable your sysmodules. Having too much sysmodules (like emuiibo) enabled will lead to system crashes bc of too much RAM usage.

**Comment by XorTroll** [comment]
This error means out of memory for title ...000C (which i think it is overlayDisp)
If the error is somehow related to emuiibo, it definitely must be that too many sysmodules are loaded.
