### ISSUE TITLE
Emulation status unknown

### ISSUE THREAD

**Issue by MegaBloopy** [XorTroll/emuiibo#53]
Amiiswap cycles through not enabled and status unknown, amiibos dont work in games, or settings, tried redownloading, wiping info, everything. nothing works

**Comment by Supersimo348** [comment]
same, i'm using fw 9.0.1

**Comment by XorTroll** [comment]
AmiISwap isn't updated for latest emuiibo, plus isn't part of this project.

**Comment by MegaBloopy** [comment]
> AmiISwap isn't updated for latest emuiibo, plus isn't part of this project.

Even without using amiiswap it is broken
