### ISSUE TITLE
Emuiibo doen't work in atmosphere 0.9.4

### ISSUE THREAD

**Issue by TheNarutimate11** [XorTroll/emuiibo#56]
I use emuiibo in system 9.0.1 and atmosphere 0.9.4 in an SD with exFat.
I know that it is often corrupted but I was using several versions of the program and it closed when entering emuiibo but now it does not want to turn on the console with the emuiibo installed.

**Comment by leo60228** [comment]
This is likely an exFAT issue if it suddenly stopped working without updating the system or Atmosphère. However, if you did update, this is likely caused by breaking changes in libstratosphere. An update is currently in development.

**Comment by TheNarutimate11** [comment]
> 
> 
> This is likely an exFAT issue if it suddenly stopped working without updating the system or Atmosphère. However, if you did update, this is likely caused by breaking changes in libstratosphere. An update is currently in development.

TNX @leo60228 . Now I updated the atmosphere and it's going well. the bad thing is that I don't know which version of amiiswap I should run it with. V0.2 and v1.0 do not activate the amiibo
