### ISSUE TITLE
[Suggestion] Amiibo redirection

### ISSUE THREAD

**Issue by KarmicBacklash** [XorTroll/emuiibo#57]
There is a continuing issue where amiibo don't work well or at all in some games due to how they are implemented. My suggestion on how to work around this is to redirect actual scanned amiibo and instead whatever emulated amiibo you have selected.

So as an example, lets say you have a real mario amiibo, and you have an emulated Link amiibo selected. Whatever you do while scanning the Mario Amiibo would instead read as the link amiibo. To be used as needed for any game. 

This does require a real amiibo for the user to use it, but I think most people have at least one amiibo.

**Comment by XorTroll** [comment]
emuiibo is exclusively made to emulate amiibo, not as a system mixing real and emulated/virtual amiibos
