### ISSUE TITLE
Update for new libnx/libstratosphere

### ISSUE THREAD

**Issue by mrdude2478** [XorTroll/emuiibo#58]
Please can you update so this is compatible with firmware 9.1.0.

Latest Atmosphere version works with this on 9.0.1 firmware - but emuiibo crashes Atmosphere on 9.1.0 firmware.

Thanks.

**Comment by XorTroll** [comment]
This is being worked on right now, 0.4.0 is on the way

**Comment by mrdude2478** [comment]
Thanks XorTroll - you never fail to deliver outstanding software :-)

**Comment by XorTroll** [comment]
Check new-strat-libnx branch, working perfectly ;)

**Comment by mrdude2478** [comment]
Thanks, that version built fine for me and is working.

Thanks for updating :-)
