### ISSUE TITLE
In-game usage like BOTW

### ISSUE THREAD

**Issue by FTLOAPK** [XorTroll/emuiibo#6]
Have tried several times and still can not be used in BOTW, perhaps the combos are not compatible in this game? Sorry but I really do not know how to use it properly.

**Comment by sorenbug** [comment]
Once you have the sysmodule enabled, and amiibo dumps in `/emuiibo`:
- Hold Dpad-Up
- Press Right Stick
- Go into whatever part of the game allows for scanning amiibo

If it still doesn't work, it might be something with how BOTW scans amiibo or your amiibo dumps.

**Comment by FTLOAPK** [comment]
Many thanks!
