### ISSUE TITLE
Crash on bootup when combos are enabled

### ISSUE THREAD

**Issue by deadair3210** [XorTroll/emuiibo#61]
Latest build of emuiibo, and atmosphere 0.10.1, on 9.0.1. Whenever I use it in its stock settings it works, but if I turn on button combos using the config file, the system will fail to boot until I either remove the boot2 flag or disable combos

**Comment by cathery** [comment]
Emuiibo runs out of memory on 0.4. babovand on discord was having the same issue, screenshot included 
![image](https://user-images.githubusercontent.com/27584451/71639162-9f683a00-2c82-11ea-8378-b8ab8fca0356.png)

**Comment by XorTroll** [comment]
Will make a quick fix asap

**Comment by XorTroll** [comment]
0.4 release binaries have been updated fixing this :P
