### ISSUE TITLE
Emuiibo Not Activate

### ISSUE THREAD

**Issue by montorio** [XorTroll/emuiibo#62]
I press R-Stick (as if it were a button) and also press the directional pad up but it does not activate. Emuiibo v0.4, atmosphere 10.1 and firmware 9.1.0

**Comment by XorTroll** [comment]
Try reading the changelog

**Comment by montorio** [comment]
Thanks...I changed it to true, and gave a memory error, but it's a bug, I'll wait for the correction and try again
