### ISSUE TITLE
[Suggestion] Rename emutool... again

### ISSUE THREAD

**Issue by CrazySteve88** [XorTroll/emuiibo#64]
The reason I'm suggesting this is that there's already a tool called EmuTool for switch that lets you "Move, Copy, Convert, Backup and Restore your SXOS and Atmosphere Emunand/emuMMC."

Site: https://gbatemp.net/threads/emutool-move-partition-emu-on-another-sd-switch-emu-type-on-sxos-and-more.550756/

I actually had no idea it existed until I googled emutool. It would be kind of confusing to have multiple EmuTool programs for the Switch.

I suggest something like emuiibo GUIibo, EmuGUIibo, EmuiiboUI, Emuiibo VACT (Virtual Amiibo Creation Tool), or Emuiibo PACT (Personal Amiibo Creation Tool).

I'm honestly getting too carried away here but you get the idea.

**Comment by XorTroll** [comment]
Not a priority, but will consider it since this might lead to confusion

**Comment by maki-chan** [comment]
Thought about that for quite some time now, how about `guiibo` (shorter than `emuGUIibo` and still quite rememberable)?

**Comment by GizmoTheGreen** [comment]
emutool is pretty generic as is, emu what?

emuiibot? emuiibo tool? emuiitool? amiibocreator? just some suggestions

**Comment by ivanmarban** [comment]
Keep it simple: emuiibo manager

**Comment by kingafro000** [comment]
Amiitool. Easy to remember, and clearly describes its purpose, which is a tool for creating amiibo. Also close to the original name so people won't even notice.

**Comment by GizmoTheGreen** [comment]
sounds great to me..!

**Comment by FearNaBoinne** [comment]
I like AmiiTool very much!

**Comment by spling-du-futur** [comment]
me too !

**Comment by XorTroll** [comment]
https://github.com/socram8888/amiitool
This is why I didn't consider this name

**Comment by spling-du-futur** [comment]
Amiibo Creator is good

**Comment by spling-du-futur** [comment]
Generiibo

**Comment by nil-code** [comment]
Emuiibo Manager

**Comment by XorTroll** [comment]
It's been a while, but I've recently considered emuiigen since emutool will soon be rewritten
