### ISSUE TITLE
"Unable to download amiibo list from amiibo API.

### ISSUE THREAD

**Issue by dothackjhe** [XorTroll/emuiibo#69]
As the title says...

**Comment by XorTroll** [comment]
Do you have internet connection...?

**Comment by dothackjhe** [comment]
Yes. By the way, I meant this in the context of using emutool. 

Here's a screenshot of the error as it takes place: https://postimg.cc/gxqscQbK

**Comment by XorTroll** [comment]
Is this still an issue?

**Comment by dothackjhe** [comment]
Sadly, it still is. I just checked.

**Comment by lsfgrd** [comment]
I'm having the same problem, but I'm trying to use emutool through wine (linux).

**Comment by XorTroll** [comment]
Try with mono, a tester had this issue and mono seemed to work fine

**Comment by dothackjhe** [comment]
What "mono"?

**Comment by dothackjhe** [comment]
@lsfgrd My computer is up-to-date with everything.

**Comment by leo60228** [comment]
@lsfgrd uses Linux. To run .NET programs (like emutool.exe), either the combination of Wine and the .NET Framework or Mono can be used. While Mono technically supports Windows, it is incredibly unlikely to help and will likely cause additional issues.

**Comment by dothackjhe** [comment]
I forgot to mention that I use Windows 10 on my desktop.

**Comment by dothackjhe** [comment]
The issue was not resolved...

**Comment by XorTroll** [comment]
#85
