### ISSUE TITLE
Issue on Yoshi's crafted world

### ISSUE THREAD

**Issue by renatosk** [XorTroll/emuiibo#7]
i posted this on gbatemp but now that issues are open here , its more appropriate.
The problem is somehow its reading the amiibo wrong , the mega yarn yoshi is supposed to unlock a yarn yoshi outfit , but its unlocking the standard yoshi amiibo outfit wich is an egg , its not my bin file because i tested with the original switch-nfp-mitm and he unlocked the right outfit.

**Comment by XorTroll** [comment]
Fixed for the next version :)
