### ISSUE TITLE
amiibo's won't work in diablo 3

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [XorTroll/emuiibo#74]
i have problems with diablo 3.
i select the amiibo with amiigo and turn on and try in diablo 3 but it says amiibo portal has been unsummoned
i tried it with amiiswap too, and the problem is the same.

i'm on fw 9.2.0 and the latest atmosphere 0.10.5

**Comment by TheOneEyedGrimReaper** [comment]
@XorTroll 
hello.
can u answer me please.
the emuiibo is not support diablo 3 or it is just a bug?

i try it out with a older version and write down the results.

**Comment by XorTroll** [comment]
Fixed for the next version :)
