### ISSUE TITLE
Emuiibo not recognized by console

### ISSUE THREAD

**Issue by Axodique** [XorTroll/emuiibo#75]
I've installed it in titles like said, but it is not recognized. The combos don't work and Amiigo says emuiibo isn't installed even though i've put the files correctly. There isn't even a settings file generated.

**Comment by Axodique** [comment]
I'm on 9.1.0 atmoshpere 0.10.4

**Comment by goofy-somebody** [comment]
the readme has not been updated to reflect the changes in atmosphere 0.10 releases

`titles` _is now_ `contents`, so put it in `atmosphere/contents/` instead

example: `<cfw>/contents/0100000000000352`

**Comment by lookye** [comment]
The file path shouldnt be the problem as emuiibo was already updated for the latest atmosphere file path structure.

@Axodique Did you enable emuiibo via its settings file in sdmc://emuiibo/ ?

**Comment by goofy-somebody** [comment]
@lookye if you read the OP, he installed it in titles based on the readme, therefore, I gave instructions on how to fix that.

**Comment by lookye** [comment]
My bad

**Comment by Frankeroni** [comment]
@goofy-somebody The readme also says:" You also have to set the **boot2 flag** in the CFW's /titles directory: <cfw>/titles/0100000000000352/flags/boot2.flag." I downloaded the latest release and the boot2 flag already is inside the flags directory. Is it remaining there? Why do the instructions say to set it?

**Comment by Axodique** [comment]
> the readme has not been updated to reflect the changes in atmosphere 0.10 releases
> 
> `titles` _is now_ `contents`, so put it in `atmosphere/contents/` instead
> 
> example: `atmosphere/contents/0100000000000352`

Oh thanks,i did not know that they changed the file structure. ( And now that i think about it that might be why my botw mods wouldn't work either)

**Comment by Axodique** [comment]
Yeah, it works now. Thanks !
