### ISSUE TITLE
Documentation on set boot2flag

### ISSUE THREAD

**Issue by duckyb** [XorTroll/emuiibo#77]
Everything written in the documentation is crystal clear, except this line:

> You also have to set the boot2 flag in the CFW's /titles directory: <cfw>/titles/0100000000000352/flags/boot2.flag

Please add a better explanation for what whis means!
Thank you

**Comment by duckyb** [comment]
Also, `/titles/` should be corrected to `/content/` and it should be noted that this app should be used along goldleaf to work. 
Or at least state that this is not a standalone/complete solution for amiibo emulation.

**Comment by XorTroll** [comment]
Indeed, I'll keep this in mind and update the documentation for the next version I'm working on

**Comment by XorTroll** [comment]
Done, README has been updated for the next version
