### ISSUE TITLE
Switch won't boot when enabled

### ISSUE THREAD

**Issue by Sevyn13** [XorTroll/emuiibo#8]
When I use Kosmos Toolbox to turn emuiibo on then reboot my switch hangs at the Nintendo Switch logo. I have to put my SD in the PC and delete the emuiibo files for it to boot.

**Comment by sorenbug** [comment]
Delete `/atmosphere/titles/0100000000000352` from your SD and then update from Kosmos Updater. If I remember correctly they now ship a working version of emuiibo for 8.0.x.

**Comment by XorTroll** [comment]
^^ true, use that until 0.2 is ready.

**Comment by Sevyn13** [comment]
So this page won't have the most up to date working version?

**Comment by king4q** [comment]
@Sevyn13 it just needs layeredfs updated & with enough knowledge & skill you can do it yourself if i’m correct without recompiling it. But I can confirm that updating using the Kosmos Updater with homebrew & then I used Choi to update without burning fuses & then rebooted to payload manually & then i’m on it using emuiibo right now so. It definitely works
