### ISSUE TITLE
emutool - AC has clones of amiibos that aren't working

### ISSUE THREAD

**Issue by Araraura** [XorTroll/emuiibo#81]
I'm trying to use the emutool to make animal crossing amiibos, but I noticed that the list has duplicates of the characters in there, and if I choose one of the duplicates, then I'm getting an error.
![1](https://user-images.githubusercontent.com/25017422/79055581-c86f7200-7c56-11ea-8db2-1faf6cc66ef0.png)
![2020-04-12 00_44_19](https://user-images.githubusercontent.com/25017422/79055584-ca393580-7c56-11ea-97ba-eb160af1b224.png)

**Comment by lookye** [comment]
1. They arent dupes. There are several amiibos/cards from the same characters.
2. The bug is known and will be fixed in the next release.

**Comment by XorTroll** [comment]
^
