### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Araraura** [XorTroll/emuiibo#82]
Hey, I followed the installation and put the amiibos in the folder and rebooted to payload, but it's still not working. Nothing happens when I press RStick + Up or any other direction, no app in the homebrew screen, nothing.

**Comment by XorTroll** [comment]
Combos are disabled by default on v0.4.
I'd wait for the next release, which is almost ready.

**Comment by Araraura** [comment]
> Combos are disabled by default on v0.4.
> I'd wait for the next release, which is almost ready.

Thanks. Also this is unrelated to this issue because I don't want to just make too many, but can we have an option to download all of the amiibos in a specific category in the next release of emutool?

**Comment by XorTroll** [comment]
I don't think I'll support that for this next release, but I'll consider it for a future release

**Comment by XorTroll** [comment]
Mind testing this for v0.5?
