### ISSUE TITLE
Emuiibo issue Atmo 0.11.1 + 9.2.0

### ISSUE THREAD

**Issue by RampageGod** [XorTroll/emuiibo#84]
Dear mr. XorTroll,
really need your help with Emuiibo. I've put "Emuiibo" folder in SD root as in instruction, but it still doesn't work. AmiSwap doesn't help either, it just say that Emuiibo is not installed. I'm confused, tried to copy or download Emuiibo from different resources, but nothing seems work . Update to 9.2.0 & Atmo 0.11.1 doesn't help much. I will appreciate your assistance!

**Comment by lookye** [comment]
There is no need to post this on multiple places. This is known and the same for every firmware/cfw update if a lot of stuff changed. Just wait for the next release which will drop very soon.

**Comment by XorTroll** [comment]
^

**Comment by RampageGod** [comment]
Sorry for my impatience, but I just tried new 0.5 version of Emuiibo and it's all the same. It just doesn't work. I will appreciate  any help on this one...
Thanks!

**Comment by XorTroll** [comment]
AmiiSwap is not updated. The only current way to control emuiibo is using the tesla overlay.

**Comment by impeeza** [comment]
Please read the manual (in this case the README.MD of the emubiio page) you will to learn what you need to install Tesla, and use the Tesla Overlay for Emubiio for configure the emulated amiibos.  once you get used to the interface, it works like a charm.

**Comment by RampageGod** [comment]
Yap, thanks! Everything works fine via Tesla Overlay. Unfortunately, it was a little obscure even with README how it works. But, I hope it's only me, who is alternatively gifted. Anyway thanks everybody for your help!

**Comment by impeeza** [comment]
Yes, tesla is still under discovery and is some obscure to use, but it will growth very soon.
