### ISSUE TITLE
Error: Caught exception (WebException) at GetAllAmiibos

### ISSUE THREAD

**Issue by dothackjhe** [XorTroll/emuiibo#85]
![emutool 0 5](https://user-images.githubusercontent.com/18740174/79578775-43260a80-80f9-11ea-94dd-305f5fd9d1b5.PNG)

The error occurs whenever I run "emutool.exe."

**Comment by XorTroll** [comment]
First of all, this is basically #69 so closing that one

**Comment by XorTroll** [comment]
I'm not completely sure why this happens

**Comment by XorTroll** [comment]
I might have a fix, will upload a test build here

**Comment by XorTroll** [comment]
[Release.zip](https://github.com/XorTroll/emuiibo/files/4493502/Release.zip)
Can somebody tell me if this works fine?
If so, will do a quick silent update

**Comment by dothackjhe** [comment]
The one in the "Release.zip" seems to work fine for me. I'm making further testing on it now.

**Comment by XorTroll** [comment]
Good to know, will wait then

**Comment by dothackjhe** [comment]
Works perfectly, so far.

**Comment by dothackjhe** [comment]
Any idea what caused the issue? Just curious.

**Comment by XorTroll** [comment]
Unsure, but found the fix on this StackOverflow post: https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel
Good to know it works :)

**Comment by XorTroll** [comment]
Updated emutool bin in the release page

**Comment by dothackjhe** [comment]
Awesome

**Comment by razorbcn** [comment]
@XorTroll tried last update. having the same issue and NetFramework is up to date.

Using emutool 0.6.1

Did not open a new issue since this is the same one happening

**Comment by rubensk8er** [comment]
having this issue to, net framework updated and the release by xor troll doesnt work either, try 3 last realsesd of emutool. it was woking fine now this happened

**Comment by UnknownDil** [comment]
everytime i open emutool i get this error: Caught exception (WebException) at GetAllAmiibos; The request was aborted: Could not create SSL/TLS secure channel.

do i need to connect pc with switch (ftp etc?) while i'm using emutool? i've disabled antivirus, i've opened it with admin privileges, done every possible thing, but i always get this error.

there is no guide to how to setup emutool, it only tells how to use it after its opened .... i even tried the release provided in this thread however still getting error

**Comment by dothackjhe** [comment]
I'm surprised to see that this issue re-occurring.
