### ISSUE TITLE
"Emuiibo not loaded" on latest version (0.5)

### ISSUE THREAD

**Issue by GarrettBK** [XorTroll/emuiibo#87]
I have _just_ updated to the latest version of emuiibo and on attempting to use it I'm informed that it's not installed. I'm on the latest Switch and Atmosphere versions (10.0.0 and 0.11.1 respectively). I've double checked that everything was installed properly and up to date and I'm still unable to use emuiibo. Any thoughts?

**Comment by lookye** [comment]
> informed that it's not installed
Where does it say, its "not installed"?

Works fine on my machine with fw10 + latest AMS.

**Comment by GarrettBK** [comment]
I use Goldleaf and I tried using Amiigo but both say that emuiibo is not present.

![F5135810-F224-46C6-9CEA-9B61937A12A2](https://user-images.githubusercontent.com/63864891/79587461-8f912c00-80a0-11ea-90f7-a54fdd0918ed.jpeg)
![602E5937-E70F-49F6-9438-A087E725A422](https://user-images.githubusercontent.com/63864891/79587465-90c25900-80a0-11ea-91a9-4a0d210e815c.jpeg)

**Comment by XorTroll** [comment]
Amiigo is not updated to use emuiibo.

**Comment by XorTroll** [comment]
Goldleaf isn't updated too, btw.

**Comment by GarrettBK** [comment]
Oh wow. What do I use instead?

**Comment by XorTroll** [comment]
Check the changelog, emuiibo has now a Tesla overlay for this.

**Comment by GarrettBK** [comment]
Sorry for the stupid question. Thank you!

**Comment by impeeza** [comment]
Is not a stupid question, I Was about to ask the same before read all the release readme.md  :D
