### ISSUE TITLE
Emutool Crash on FTP Timeout

### ISSUE THREAD

**Issue by impeeza** [XorTroll/emuiibo#88]
Hi, By now EmuTool works very well, but I just ran in a pickle.

Trying to create a new Amiibo on my Switch, but writing the bad address for FTP upload, and then I get the expected "Timed out trying to connect!" error, but pressing the OK button, the program closes.

the correct action should be to return to main window.

if I correct the IP address the switch the Amiibo is well created and no problem nor error.

if you look at the picture I did write the 192.168.100.15 FTP address and it should be 192.168.100.14
![image](https://user-images.githubusercontent.com/41979604/79627577-268cd100-80ff-11ea-9b95-bb589f6a27bf.png)
after this error the program crash and closes

but using the correct address all works fine.
![image](https://user-images.githubusercontent.com/41979604/79627581-2b518500-80ff-11ea-9db4-f110bac6434a.png)

**Comment by XorTroll** [comment]
> Trying to create a new Amiibo on my Switch, but writing the bad address for FTP upload, and then I get the expected "Timed out trying to connect!" error, but pressing the OK button, the program closes.
the correct action should be to return to main window.

Nah, this is done in purpose

**Comment by XorTroll** [comment]
Any kind of error in emutool closes the application

**Comment by impeeza** [comment]
He he he,  that's kinky,  thanks a lot for all your work
