### ISSUE TITLE
Smash Ultimate not saving data

### ISSUE THREAD

**Issue by ruvaldak** [XorTroll/emuiibo#9]
Super Smash Bros Ultimate reads the emulated amiibos fine, and says it saves when you're done with the amiibos, however scanning the same amiibo again makes you register it again, and it won't let you bring one into battle. 
Also, the key combos are a little wonky, and don't always work. Basically I have to enable amiibo emulation before needing to read the amiibo, and disable it immediately afterwards. They apparently can't be emulated while it's searching for amiibos, if that makes sense. Also when I use right+down to disable, it doesn't disable until, like, I go to another screen, which can lead to getting stuck in dialogue boxes complaining this amiibo isn't compatible or whatever

**Comment by XorTroll** [comment]
0.2 is adding saving, even the latest commits have it.

**Comment by IAmTheRealLinkle** [comment]
Is there any place to get a version with the latest commits?

**Comment by HookedBehemoth** [comment]
You can compile it yourself.

**Comment by Leeserh** [comment]
How would someone compile a master? I have Googled and am still unsure as there are multiple ways to do it. Thanks!

**Comment by HookedBehemoth** [comment]
Install devkitpro for switch-dev. (https://devkitpro.org/wiki/Getting_Started)
Compile and install latest libnx master (https://github.com/switchbrew/libnx) (`make && make install`)
Compile this repo. (`make`)

**Comment by Leeserh** [comment]
Thank you so much! It's a wonderful tool and I can't wait for 2.0!

**Comment by IAmTheRealLinkle** [comment]
Thank you. I will give that a try today actually!

**Comment by Leeserh** [comment]
Hmm. I had no luck. When I tried to compile emuiibo after installing libnx it said it couldn't find -lstratosphere. Are there particular directories to keep in mind? Also, by compile do you mean clone? Thanks again!

**Comment by IAmTheRealLinkle** [comment]
I got the same thing, I love it😂 sorry for cluttering the issue with help.

**Comment by HookedBehemoth** [comment]
Try this:
`cd libstratosphere/ && make && cd ..`

**Comment by Leeserh** [comment]
Thank you! Trying now.

**Comment by Leeserh** [comment]
I think it worked! I have an .nro, an .nsp, and an .elf  of emuuibo now.

**Comment by Leeserh** [comment]
excuse me, emuiibo. and an .nso, not nro

**Comment by Leeserh** [comment]
Am unsure what to do with them from here so I'd greatly appreciate one last moment of your time if you'd care to give it. Thanks!

**Comment by sorenbug** [comment]
Put the `nsp` as `sd:/atmosphere/titles/0100000000000352/exefs.nsp`

**Comment by Leeserh** [comment]
Thanks!

**Comment by Leeserh** [comment]
So, I loaded up the nsp and all seemed well until the game got stuck attempting to read the amiibo. Very weird.

**Comment by Leeserh** [comment]
Can anyone confirm that this is a problem for them too? Any idea on a time-frame for new release?

**Comment by HookedBehemoth** [comment]
I don't have the problem.

**Comment by Leeserh** [comment]
Then I must have definitely done something wrong compiling the master. It had a problem compiling atmosphere title data for me. I completely understand if not (I'm just a pesky rando), but would you be willing to send me a file of the emuiibo data you have? Again, completely understand if not.

**Comment by Leeserh** [comment]
Unfortunately, I'm still having the same problem, which is that Smash Ultimate gets stuck trying to read the amiibo I've selected from amiiswap. I'm pressing r plus the up d-pad before I start the app. Any ideas?

**Comment by deurk** [comment]
@Leeserh Using latest release, do you still have the same issue?

**Comment by Leeserh** [comment]
@deurk  Hey! Thanks for asking. I actually switched over to ReiNX and emuiibo 2.0 is running on that without issue.
