### ISSUE TITLE
Download all Amiibos at once

### ISSUE THREAD

**Issue by rusagent** [XorTroll/emuiibo#90]
Heya,

wanted to ask if there is the possibility to dump all amiibos at once to put them on the SD?
Some commandline option with the tool or so maybe?

**Comment by Slluxx** [comment]
here, i compiled the program with a few changes. now you can dump all at once.
ill do an official pr soon
[Release.zip](https://github.com/XorTroll/emuiibo/files/4519474/Release.zip)

**Comment by rusagent** [comment]
Hectic! Cheers!

**Comment by Slluxx** [comment]
added the PR

**Comment by XorTroll** [comment]
Merged the PR
