### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by chimel23** [XorTroll/emuiibo#92]
All I get is "emuiibo was not accessed." Why???

**Comment by impeeza** [comment]
could you see the emuiibo.log.

**Comment by chimel23** [comment]
No. I was missing a file but it still doesn’t work

**Comment by Kemerd** [comment]
Same exact issue. Latest firmware 10.0.1, latest Atmosphere 0.11.1, all games

**Comment by Kemerd** [comment]
**Edit:** Found the fix. You need to open the Tesla menu, go to Sysmodules, enable emuiibo for auto-boot on startup. Seems to work now.

**Comment by ilymbrdc15** [comment]
Hi! @Kemerd. What do you mean by enabling emuiibo for auto-boot on startup? It just prompts here that "No sysmodules found!". I have same issue with the author.

CFW: 10.0.1 | AMS 0.11.1

**Comment by ilymbrdc15** [comment]
> **Edit:** Found the fix. You need to open the Tesla menu, go to Sysmodules, enable emuiibo for auto-boot on startup. Seems to work now.

Hi! @Kemerd. What do you mean by enabling emuiibo for auto-boot on startup? It just prompts here that "No sysmodules found!". I have same issue with the author.

CFW: 10.0.1 | AMS 0.11.1

**Comment by lookye** [comment]
@chimel23 You describe an issue in a very short sentence. Please write everything down as detailed as possible. Where does the message come? What Firmware, which CFW, which emuiibo version etc..

**Comment by kamanchak** [comment]
emuiibo doesn´t work  with firmware 9.2.0  with Athmosphere 12

**Comment by lookye** [comment]
It works fine if you follow all steps and dont fuck something up.
Read this https://github.com/XorTroll/emuiibo/blob/master/Usage.md

**Comment by impeeza** [comment]
That's my exactly configuration and all works just fine, please RTFM

**Comment by Anti-Apple4life** [comment]
same, it lets me load the overlay and amiibo, but when I connect it, it says not intercepting game and does not work.

**Comment by kamanchak** [comment]
> same, it lets me load the overlay and amiibo, but when I connect it, it says not intercepting game and does not work.

it always works on the second attempt to read the amiibo, did you do that?

**Comment by Anti-Apple4life** [comment]
Im using it on smash, so there is no second time Sent from Mail for Windows 10 From: kamanchakSent: Monday, May 4, 2020 3:03 PMTo: XorTroll/emuiiboCc: Anti-Apple4life; CommentSubject: Re: [XorTroll/emuiibo] It doesn't work (#92) same, it lets me load the overlay and amiibo, but when I connect it, it says not intercepting game and does not work.it always works on the second attempt to read the amiibo, did you do that?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kyriakos2008** [comment]
> It works fine if you follow all steps and dont fuck something up.
> Read this https://github.com/XorTroll/emuiibo/blob/master/Usage.md

i followed the steps one by one and still says "emuiibo was not accessed" and i tried rebooting and still the same.

Atmospere version: 10.1.0
AMS 0.14.1
