### ISSUE TITLE
Crash when registering multiple amiibos in succession 

### ISSUE THREAD

**Issue by Localhorst86** [XorTroll/emuiibo#94]
Firmware version: 10.0.0 (Sysnand) 
Atmosphere Version: 0.11.1
Emuiibo Version 0.5.0 using the tesla overlay
Game affected: Super Smash Brothers 01006A800016E000 Update 15 (v983040)
Atmosphere error code 2345-0002 (0x559)

Issue: when registering new amiibos in succession in the amiibo menu of the game, emuiibo will cause atmosphere to crash.

Steps to reproduce:
1. Create 2 or more new amiibos using emu tool and transfer them over to the switch
2. Enable emuiibo using the tesla overlay and start the game.
3. Access the amiibo menu from the "other modes" menu of the game
4. When prompted, open the tesla overlay and connect the first brand new amiibo.
5. Selecting the outfit for the emuiibo and return to the menu.
6. When prompted by the game, save the data to the amiibo to register it for smash.
7. When prompted by the game, disconnect the amiibo using the tesla overlay.
8. Select the next brand new amiibo in the tesla overlay and connect it.
9a. In some occasions, atmosphere might already crash at this point.
9b. If atmosphere hasn't crashed yet, continue selecting the outfit.
10. If atmosphere hasn't crashed yet, leave the amiibo menu.
11. When prompted, let the system write back to the amiibo.
This is the farthest I was able to ever get. The second amiibo will not be registered at this point, the system needs to be rebooted and I can repeat the process. Rebooting the system in between the two registration processes will prevent the crash. 

Attached:
Atmosphere crash log and memory dump
[01587656896_0100000000000352.log](https://github.com/XorTroll/emuiibo/files/4523757/01587656896_0100000000000352.log)
[01587656896_0100000000000352.zip](https://github.com/XorTroll/emuiibo/files/4523764/01587656896_0100000000000352.zip)

**Comment by XorTroll** [comment]
I did run into this issue once, just thought it was too rare to actually worry about it

**Comment by Localhorst86** [comment]
> I did run into this issue once, just thought it was too rare to actually worry about it

Unfortunately, I can reproduce this on every single instance. :)

**Comment by XorTroll** [comment]
[emuiibo.zip](https://github.com/XorTroll/emuiibo/files/4523843/emuiibo.zip)
I have an idea, mind trying this build?
Just replace the exefs.nsp file in atmosphere/contents/0100000000000352 with the emuiibo.nsp file here (rename it to exefs.nsp)

**Comment by Localhorst86** [comment]
That certainly lessened the issue. The crash now occurs on every fourth amiibo to be registered. I was able to reproduce this crash 3 times in a row on the fourth amiibo with the exefs.nsp file from your last post.

**Comment by XorTroll** [comment]
Mind sending the emuiibo log file (emuiibo.log) located in emuiibo/ directory?
You might need to re-reproduce the crash to generate logs again

**Comment by Localhorst86** [comment]
[emuiibo.log](https://github.com/XorTroll/emuiibo/files/4533145/emuiibo.log)
Of course. Here it is. The crash happened on the 4th amiibo, once it crashed I didn't restart the console but powered it down, otherwise it would create a new blank log in place when rebooting.

**Comment by Leeserh** [comment]
Can also confirm that this happens. The build you posted prevents crashing until 4 amiibos are read, though.

**Comment by XorTroll** [comment]
[SdOut.zip](https://github.com/XorTroll/emuiibo/files/4565584/SdOut.zip)
Mind trying this one?

**Comment by Localhorst86** [comment]
Unfortunately, that didn't remedy the issue, allthough the crash is now not as "consistent" as it was before. Before, it would crash when scanning the forth amiibo. Now it crashes on the fifth amiibo, but sometimes it crashes when it is scanned, sometimes it crashes *after* writing to the fifth amiibo.

Here's a new crash dump and emuiibo log. 
[Download.zip](https://github.com/XorTroll/emuiibo/files/4566044/Download.zip)

**Comment by kamanchak** [comment]
and if emuiibo is deactivated after reading the amiibo, and it is activated again when we put a new amiibo

**Comment by evertongomesjob** [comment]
I have been facing the issue while using 4 or 5 amiibos the game crashes. And when turning the console on again, it doesn't work anymore. I have to go to the computer and copy and paste de folder to micro sd card again. Is there any other solution?

**Comment by XorTroll** [comment]
Try again with version 0.6
