### ISSUE TITLE
Too many sysmodules accessing time:u service

### ISSUE THREAD

**Issue by dazzaXx** [XorTroll/emuiibo#96]
Firmware 10.0.1 / Atmosphere 0.11.1 / Hekate v5.1.4 / Kosmos v15.6

After enabling Emuiibo in the Kosmos Toolbox and rebooting, sys-botbase ended up crashing first out of nowhere so i disabled that first. Then Emuiibo started to crash the system a few seconds after rebooting. After disabling both sys-botbase and Emuiibo, i re-enabled sys-botbase and the crashing ceased.

I assume it's because it needs updating to support 10.0.1, but i just thought i'd mention this here incase it is to do with 10.0.1.

Thanks.

**Comment by XorTroll** [comment]
Crash report? Error code?

**Comment by dazzaXx** [comment]
The error code for when it makes sys-botbase crash is 2116-0801 (0x64274)

and it seems when attempting to run hb-menu with emuiibo just enabled, it throws a 2345-0038 (0x4d59) error.

**Comment by XorTroll** [comment]
On that last error, do you have any other sysmodules running aside from emuiibo?

**Comment by dazzaXx** [comment]
i think ftpd-light, sys-con and tesla are also enabled.

**Comment by XorTroll** [comment]
Try again, disabling ftpd or sys-con

**Comment by dazzaXx** [comment]
i had also disabled ftpd-light, but it seems that wasn't a problem once i had re-enabled it.

**Comment by dazzaXx** [comment]
also to note, when i had disabled sys-botbase it was crashing something that had the titleid of 010000000000100D which ive never seen before and have no idea what it is.

**Comment by dazzaXx** [comment]
Ahh alright, well i'm glad i know now what was happening so i can refrain it from happening again, i thought it had something to do with the firmware version xD still learning the ropes of the switch scene, i learn a little everyday. Thanks again!

**Comment by XorTroll** [comment]
I'll talk with other devs and think of a possible solution

**Comment by dazzaXx** [comment]
Just a quick question, i've read that emuiibo supports .bin dumps of amiibos but i cannot figure out where to put them, do you put them straight on the sd card or do you have to use the emutool?

**Comment by XorTroll** [comment]
Just place them in emuiibo/amiibo

**Comment by dazzaXx** [comment]
Cheers :P

**Comment by Eds1989** [comment]
I may have the same issue.
On FW 10.0 Atmosphere 0.11.0

If I have all of my sysmodules enabled, my titles crash whether it be hdmenu or actual games.
I thought I had narrowed it down to nx-ovlloader, as if I removed that and that alone, the crashes stopped.

I opened an issue on their repo here:
https://github.com/WerWolv/nx-ovlloader/issues/3

If I disabled all sys-modules though, and re-enabled them one at a time, I found I could run them all, until I added either ldn-mitm or emuiibo.

My error codes were different, and I would have thought if it was a time service access issue, I would have still seen an issue after removing nx-ovlloader?
Could this be the same?

**Comment by dazzaXx** [comment]
For me, it's sys-botbase that's the main culprit of those crashes, still even now, attempting to install and run Fizeau results in the same random crashes when attempting to run the hbmenu or a game. Guess it's doing something that the other ones don't like.

**Comment by AR3FACT** [comment]
I only have emuiibo and the error code 2345-0038 still appear when I go to the album

**Comment by Shadow511** [comment]
Hello I have a atmosphere's cfw crash when I launch the hombrew menu by the apps and the album, I m on atmosphere 10.1.0 and ams 0.14.1, the error code is 2345-0038 too

**Comment by XorTroll** [comment]
emuiibo no longer uses time services, so this issue no longer makes sense in emuiibo's context
