### ISSUE TITLE
(ACNH) Villagers in Photopia crash the game

### ISSUE THREAD

**Issue by JTT28** [XorTroll/emuiibo#97]
Hello devs,

Whenever I try to interact with a villager spawned via emuiibo in photopia, there is a chance that my system will crash.

Here's the Atmosphere crash info:
Error Code: 2345-0002 (0x559)
Program: 0100000000000352
Firmware: 10.0.0 (Atmosphere 0.11.1-master-d81a3bdc)

This happens seemingly at random when I try to do anything with them (change their clothes, change their reactions, remove them, _move them around_)

On a different note, my system doesn't crash when inviting villagers to the campsite via the nook stop.

How do I fix this?

**Comment by GizmoTheGreen** [comment]
I don't think interacting with amiibo animals in photopia has anything to do with emuiibo, emuiibo is only involved when you "scan" them to bring them in. anything after that is either a problem of your amiibo dumps (if not using virtual, but bin files?) or your game / cfw.

**Comment by JTT28** [comment]
Update:
I've found that disabling emuiibo immediately after spawning the villager in doesn't crash the game.

Here's my procedure of doing things:
- Arrive on Harv's Island
- Enable emuiibo
- Enter the Photopia building
- Spawn in the villager via emuiibo
- Disable emuiibo

I can do this multiple times in succession and the game doesn't crash, but the moment I leave emuiibo on, it crashes.

**Comment by kamanchak** [comment]
same issue, when  i load amiibo so fast it crash

**Comment by skyclanforlife** [comment]
Odd, never had this issue

**Comment by FreeTigerman** [comment]
same issue

**Comment by igromanru** [comment]
@JTT28 yeah, this is more like it.  
I also got the feeling that the problem is that the emuiibo is on all the time. I tried to disable it after each villager but it still happens.  
I'm missing the old "enable once" option.

**Comment by XorTroll** [comment]
Try again with version 0.6
