### ISSUE TITLE
Emuiibo was not accessed.

### ISSUE THREAD

**Issue by MateMate123** [XorTroll/emuiibo#98]
I get this error when i try to open it via the tesla menu. 

Here is a [Link](https://www.youtube.com/watch?v=FUV0BmYEJlQ&feature=youtu.be)

**Comment by lookye** [comment]
Update your Tesla files. They´re not up2date.

**Comment by MateMate123** [comment]
> Update your Tesla files. They´re not up2date.

I just updated. Still the same error

**Comment by lookye** [comment]
1. You give an insufficient amount of information.
2. Make sure everything is set up correctly
3. Read this: https://github.com/XorTroll/emuiibo/blob/master/Usage.md

**Comment by MateMate123** [comment]
i did all that. I installed amiibos with and without FTP. I reinstalled NXovloader, Tesla, and emuiibo. I tried reinstalling atmosphere

**Comment by lookye** [comment]
If everything is up2date (Atmosphere, Tesla (Tesla-menu and ovlloader), emuiibo) it should work as intended.
Beside that: What´s the content you have in sdmc://emuiibo/amiibo?

**Comment by MateMate123** [comment]
Nothing else in the folder, ill try to reinstall atmosphere again though

**Comment by lookye** [comment]
So if you have nothing in the folder, you dont have any amiibos (.bin files or amiibos made with emutool). You should come over to [discord](https://discord.gg/3KpFyaH), as it seems you did wrong in the setup and go through the usage.md i linked you above step by step.

**Comment by MateMate123** [comment]
I meant i had nothing else than the amiibos

**Comment by MateMate123** [comment]
Okay. So i reinstalled atmosphere, Emuiibo, ovloader, and tesla menu. And it finally worked!
