### ISSUE TITLE
BOTW crash when using successively amiibos.

### ISSUE THREAD

**Issue by Ronanbourg** [XorTroll/emuiibo#99]
Firmware version: 9.2 (EmuNand) and 10.0.0 (EmuNand).
 Atmosphere Version: 0.11.1
 Emuiibo Version 0.5.0 using the tesla overlay
 Game affected: Zelda Breath of the Wild.

Issue : when emuiibo is used too many times, the game crashes.

Reproduce the issue : use between 15 and 40 time the emuiibo in a row, collecting chests or not.

It's seems very close to the issue number 94. 

I tried the exefs.nsp you published on that issue, and the problem seems gone (it crashed, but after a hundred attemps).

Do you need a crash report ? If yes, in witch directory can I find it ?

Thanks very much.

Ronan.

**Comment by XorTroll** [comment]
#94
